WITH PATIENTS AS (
	SELECT DISTINCT
		ENCOUNTER.ENCNTR_ID,
		ENCOUNTER.PERSON_ID,
		ENCNTR_ALIAS.ALIAS AS FIN,
		ENCOUNTER.ARRIVE_DT_TM,
		ENCOUNTER.REG_DT_TM
	FROM
		ENCNTR_ALIAS,
		ENCOUNTER
	WHERE
	    ENCNTR_ALIAS.ALIAS IN @prompt('Enter value(s) for Alias','A',,Multi,Free,Persistent,,User:0)
		AND ENCNTR_ALIAS.ENCNTR_ALIAS_TYPE_CD = 619 -- FIN NBR
		AND ENCNTR_ALIAS.ACTIVE_IND = 1
		AND ENCNTR_ALIAS.ENCNTR_ID = ENCOUNTER.ENCNTR_ID
), TFR_FACILITY AS (
	SELECT DISTINCT
		PATIENTS.ENCNTR_ID,
		PATIENTS.PERSON_ID,
		ENCOUNTER.ENCNTR_ID AS TFR_ENCNTR_ID
	FROM
		ENCOUNTER,
		PATIENTS
	WHERE
		PATIENTS.PERSON_ID = ENCOUNTER.PERSON_ID
		AND ENCOUNTER.DISCH_DT_TM BETWEEN PATIENTS.REG_DT_TM - 1 AND PATIENTS.REG_DT_TM
		AND ENCOUNTER.ENCNTR_TYPE_CLASS_CD IN (
			42631, -- Inpatient
			55851, -- Emergency
			688523 -- Observation
		)
), ENCNTR_LIST AS (
	SELECT ENCNTR_ID FROM PATIENTS
	UNION
	SELECT TFR_ENCNTR_ID AS ENCNTR_ID FROM TFR_FACILITY
)

SELECT DISTINCT
	-- PATIENTS.ENCNTR_ID,
	PATIENTS.FIN,
	-- CLINICAL_EVENT.EVENT_END_DT_TM,
	TO_CHAR(pi_from_gmt(CLINICAL_EVENT.EVENT_END_DT_TM, 'America/Chicago'), 'YYYY-MM-DD"T"HH24:MI:SS') AS EVENT_DATETIME,
	CLINICAL_EVENT.EVENT_ID,
	pi_get_cv_display(CLINICAL_EVENT.EVENT_CD) AS EVENT,
	TO_NUMBER(REGEXP_REPLACE(CLINICAL_EVENT.RESULT_VAL, '>|<')) AS RESULT_VAL,
	pi_get_cv_display(CLINICAL_EVENT.RESULT_UNITS_CD) AS RESULT_UNITS
FROM
	CLINICAL_EVENT,
	PATIENTS
WHERE
	CLINICAL_EVENT.ENCNTR_ID IN (SELECT DISTINCT ENCNTR_ID FROM ENCNTR_LIST)
	AND CLINICAL_EVENT.EVENT_CLASS_CD = 159 -- NUM
	AND PATIENTS.PERSON_ID = CLINICAL_EVENT.PERSON_ID
	AND CLINICAL_EVENT.EVENT_CD IN (
		30098, -- Systolic Blood Pressure
		134401648 -- Arterial Systolic BP 1
	)
	AND CLINICAL_EVENT.EVENT_END_DT_TM > PATIENTS.ARRIVE_DT_TM - 0.5
	AND CLINICAL_EVENT.VALID_UNTIL_DT_TM > DATE '2099-12-31'
