WITH PATIENTS AS (
	SELECT DISTINCT
		ENCOUNTER.ENCNTR_ID,
		ENCOUNTER.PERSON_ID,
		ENCOUNTER.REG_DT_TM
	FROM
		DIAGNOSIS,
		ENCOUNTER,
		NOMENCLATURE,
		PERSON
	WHERE
		ENCOUNTER.ORGANIZATION_ID = 1 -- Memorial Hermann Hospital
		AND ENCOUNTER.REG_DT_TM BETWEEN 
			pi_to_gmt(
				TO_DATE(
					@Prompt('Enter begin date', 'D', , mono, free, persistent, {'07/01/2017 00:00:00'}, User:0), 
					pi_get_dm_info_char_gen('Date Format Mask|FT','PI EXP|Systems Configuration|Date Format Mask')
				), 
				pi_time_zone(1, @Variable('BOUSER'))
			)
			AND pi_to_gmt(
				TO_DATE(
					@Prompt('Enter end date', 'D', , mono, free, persistent, {'08/01/2021 00:00:00'}, User:1), 
					pi_get_dm_info_char_gen('Date Format Mask|FT','PI EXP|Systems Configuration|Date Format Mask')
				) - 1/86400, 
				pi_time_zone(1, @Variable('BOUSER'))
			)
		AND ENCOUNTER.LOC_FACILITY_CD = 3310 -- HH HERMANN
		-- AND ENCOUNTER.ADMIT_SRC_CD = 9061 -- Emergency Room
		AND ENCOUNTER.ENCNTR_ID = DIAGNOSIS.ENCNTR_ID
		AND DIAGNOSIS.DIAG_TYPE_CD = 26244 -- Final
		AND DIAGNOSIS.DIAG_PRIORITY = 1
		AND DIAGNOSIS.NOMENCLATURE_ID = NOMENCLATURE.NOMENCLATURE_ID
		AND REGEXP_INSTR(NOMENCLATURE.SOURCE_IDENTIFIER, '^I61') > 0
		AND NOMENCLATURE.SOURCE_VOCABULARY_CD = 641836527 -- ICD-10-CM
		AND NOMENCLATURE.PRINCIPLE_TYPE_CD = 751 -- Disease or Syndrome
		AND ENCOUNTER.PERSON_ID = PERSON.PERSON_ID
		AND TRUNC((TRUNC(pi_from_gmt(ENCOUNTER.REG_DT_TM, 'America/Chicago')) - TRUNC(pi_from_gmt(PERSON.BIRTH_DT_TM, 'America/Chicago'))) / 365.25, 0) >= 18
), LABS AS (
	SELECT DISTINCT
		PATIENTS.ENCNTR_ID,
		PATIENTS.REG_DT_TM,
		CLINICAL_EVENT.EVENT_END_DT_TM,
		-- pi_from_gmt(CLINICAL_EVENT.EVENT_END_DT_TM, 'America/Chicago') AS EVENT_DATETIME,
		ABS(1 - (CLINICAL_EVENT.EVENT_END_DT_TM - PATIENTS.REG_DT_TM)) AS ADMIT_LAB_24HR_DIFF,
		CLINICAL_EVENT.EVENT_ID,
		pi_get_cv_display(CLINICAL_EVENT.EVENT_CD) AS EVENT,
		CLINICAL_EVENT.RESULT_VAL,
		pi_get_cv_display(CLINICAL_EVENT.RESULT_UNITS_CD) AS RESULT_UNITS
	FROM
		CLINICAL_EVENT,
		PATIENTS
	WHERE
		PATIENTS.ENCNTR_ID = CLINICAL_EVENT.ENCNTR_ID
		AND CLINICAL_EVENT.EVENT_CLASS_CD IN (
			159, -- NUM
			162 -- TXT
		)
		AND PATIENTS.PERSON_ID = CLINICAL_EVENT.PERSON_ID
		AND CLINICAL_EVENT.EVENT_CD IN (
			31821, -- HDL
			32227, -- LDL (Calculated)
			32228, -- LDL Direct
			134422765, -- Glasgow Coma Score
			134590635, -- NIH Stroke Score
			297370347, -- NIH Stroke Scale Assessment
			1466654557, -- MRS Modified Rankin Scales
			1466654584, -- MRS Total
			3398081391 -- Modified Rankin Scale Score
		)
		AND CLINICAL_EVENT.VALID_UNTIL_DT_TM > DATE '2099-12-31'
), ADMIT_LABS AS (
	SELECT
		ENCNTR_ID,
		EVENT,
		MIN(RESULT_VAL) KEEP (DENSE_RANK FIRST ORDER BY EVENT_END_DT_TM, EVENT_ID) AS LAB_RESULT,
		'ADMIT' AS LAB_TIMING
	FROM LABS
	GROUP BY
		ENCNTR_ID,
		EVENT
), DC_LABS AS (
	SELECT
		ENCNTR_ID,
		EVENT,
		MIN(RESULT_VAL) KEEP (DENSE_RANK LAST ORDER BY EVENT_END_DT_TM, EVENT_ID) AS LAB_RESULT,
		'DISCH' AS LAB_TIMING
	FROM LABS
	WHERE 
		EVENT IN (
			'Glasgow Coma Score',
			'MRS Modified Rankin Scales',
			'MRS Total',
			'Modified Rankin Scale Score'
		)
	GROUP BY
		ENCNTR_ID,
		EVENT
), DAY_ONE_LABS AS (
	SELECT
		ENCNTR_ID,
		EVENT,
		MIN(RESULT_VAL) KEEP (DENSE_RANK FIRST ORDER BY ADMIT_LAB_24HR_DIFF) AS LAB_RESULT,
		'24_HR' AS LAB_TIMING
	FROM LABS
	WHERE 
		EVENT IN (
			'Glasgow Coma Score',
			'NIH Stroke Score',
			'NIH Stroke Scale Assessment'
		)
	GROUP BY
		ENCNTR_ID,
		EVENT
), ALL_LABS AS (
	SELECT * FROM ADMIT_LABS

	UNION

	SELECT * FROM DC_LABS

	UNION

	SELECT * FROM DAY_ONE_LABS
)

SELECT DISTINCT
	ALL_LABS.*,
	ENCNTR_ALIAS.ALIAS AS FIN
FROM
	ALL_LABS,
    ENCNTR_ALIAS
WHERE
	ALL_LABS.ENCNTR_ID = ENCNTR_ALIAS.ENCNTR_ID
	AND ENCNTR_ALIAS.ENCNTR_ALIAS_TYPE_CD = 619 -- FIN NBR
	AND ENCNTR_ALIAS.ACTIVE_IND = 1