WITH PATIENTS AS (
	SELECT DISTINCT
		ENCOUNTER.ENCNTR_ID,
		ENCOUNTER.PERSON_ID,
		ENCNTR_ALIAS.ALIAS AS FIN,
		ENCOUNTER.REG_DT_TM
	FROM
		ENCNTR_ALIAS,
		ENCOUNTER
	WHERE
	    ENCNTR_ALIAS.ALIAS IN @prompt('Enter value(s) for Alias','A',,Multi,Free,Persistent,,User:0)
		AND ENCNTR_ALIAS.ENCNTR_ALIAS_TYPE_CD = 619 -- FIN NBR
		AND ENCNTR_ALIAS.ACTIVE_IND = 1
		AND ENCNTR_ALIAS.ENCNTR_ID = ENCOUNTER.ENCNTR_ID
), VASOP_MEDS AS (
    SELECT DISTINCT
        PATIENTS.ENCNTR_ID,
		PATIENTS.FIN,
        CLINICAL_EVENT.EVENT_END_DT_TM,
        CLINICAL_EVENT.EVENT_ID,
        pi_get_cv_display(CLINICAL_EVENT.EVENT_CD) AS MEDICATION
    FROM
        CE_MED_RESULT,
        CLINICAL_EVENT,
        PATIENTS
    WHERE
        PATIENTS.ENCNTR_ID = CLINICAL_EVENT.ENCNTR_ID
        AND CLINICAL_EVENT.EVENT_CLASS_CD = 158 -- MED
        AND PATIENTS.PERSON_ID = CLINICAL_EVENT.PERSON_ID
        AND CLINICAL_EVENT.EVENT_CD IN (
            37556849, -- EPINephrine
            37557691, -- norepinephrine
            37557816, -- phenylephrine
            37558323, -- vasopressin
            37558389 -- DOPamine
        )
        AND CLINICAL_EVENT.EVENT_END_DT_TM < PATIENTS.REG_DT_TM + 3
        AND CLINICAL_EVENT.VALID_UNTIL_DT_TM > DATE '2099-12-31'
        AND CLINICAL_EVENT.EVENT_ID = CE_MED_RESULT.EVENT_ID
        AND CE_MED_RESULT.VALID_UNTIL_DT_TM > DATE '2099-12-31'
)

SELECT
	-- ENCNTR_ID,
	FIN,
	MEDICATION,
	TO_CHAR(pi_from_gmt(MIN(EVENT_END_DT_TM), 'America/Chicago'), 'YYYY-MM-DD"T"HH24:MI:SS') AS VASOP_START_DATETIME,
	MAX(EVENT_END_DT_TM) - MIN(EVENT_END_DT_TM) AS VASOP_DURATION
FROM VASOP_MEDS
GROUP BY
	-- ENCNTR_ID,
	FIN,
	MEDICATION
)
