WITH PATIENTS AS (
	SELECT DISTINCT
		ENCOUNTER.ENCNTR_ID,
		ENCOUNTER.PERSON_ID,
		ENCOUNTER.REG_DT_TM
	FROM
		DIAGNOSIS,
		ENCOUNTER,
		NOMENCLATURE,
		PERSON
	WHERE
		ENCOUNTER.ORGANIZATION_ID = 1 -- Memorial Hermann Hospital
		AND ENCOUNTER.REG_DT_TM BETWEEN 
			pi_to_gmt(
				TO_DATE(
					@Prompt('Enter begin date', 'D', , mono, free, persistent, {'07/01/2017 00:00:00'}, User:0), 
					pi_get_dm_info_char_gen('Date Format Mask|FT','PI EXP|Systems Configuration|Date Format Mask')
				), 
				pi_time_zone(1, @Variable('BOUSER'))
			)
			AND pi_to_gmt(
				TO_DATE(
					@Prompt('Enter end date', 'D', , mono, free, persistent, {'08/01/2021 00:00:00'}, User:1), 
					pi_get_dm_info_char_gen('Date Format Mask|FT','PI EXP|Systems Configuration|Date Format Mask')
				) - 1/86400, 
				pi_time_zone(1, @Variable('BOUSER'))
			)
		AND ENCOUNTER.LOC_FACILITY_CD = 3310 -- HH HERMANN
		-- AND ENCOUNTER.ADMIT_SRC_CD = 9061 -- Emergency Room
		AND ENCOUNTER.ENCNTR_ID = DIAGNOSIS.ENCNTR_ID
		AND DIAGNOSIS.DIAG_TYPE_CD = 26244 -- Final
		AND DIAGNOSIS.DIAG_PRIORITY = 1
		AND DIAGNOSIS.NOMENCLATURE_ID = NOMENCLATURE.NOMENCLATURE_ID
		AND REGEXP_INSTR(NOMENCLATURE.SOURCE_IDENTIFIER, '^I61') > 0
		AND NOMENCLATURE.SOURCE_VOCABULARY_CD = 641836527 -- ICD-10-CM
		AND NOMENCLATURE.PRINCIPLE_TYPE_CD = 751 -- Disease or Syndrome
		AND ENCOUNTER.PERSON_ID = PERSON.PERSON_ID
		AND TRUNC((TRUNC(pi_from_gmt(ENCOUNTER.REG_DT_TM, 'America/Chicago')) - TRUNC(pi_from_gmt(PERSON.BIRTH_DT_TM, 'America/Chicago'))) / 365.25, 0) >= 18
), VASOP_MEDS AS (
    SELECT DISTINCT
        PATIENTS.ENCNTR_ID,
        CLINICAL_EVENT.EVENT_END_DT_TM,
        -- pi_from_gmt(CLINICAL_EVENT.EVENT_END_DT_TM, 'America/Chicago') AS EVENT_DATETIME,
        CLINICAL_EVENT.EVENT_ID,
        pi_get_cv_display(CLINICAL_EVENT.EVENT_CD) AS MEDICATION,
        -- CE_MED_RESULT.ADMIN_DOSAGE,
        -- pi_get_cv_display(CE_MED_RESULT.DOSAGE_UNIT_CD) AS DOSAGE_UNIT,
        -- CE_MED_RESULT.INFUSION_RATE,
        -- pi_get_cv_display(CE_MED_RESULT.INFUSION_UNIT_CD) AS INFUSION_UNIT,
        -- pi_get_cv_display(CE_MED_RESULT.ADMIN_ROUTE_CD) AS ADMIN_ROUTE,
        -- pi_get_cv_display(CE_MED_RESULT.IV_EVENT_CD) AS IV_EVENT
    FROM
        CE_MED_RESULT,
        CLINICAL_EVENT,
        PATIENTS
    WHERE
        PATIENTS.ENCNTR_ID = CLINICAL_EVENT.ENCNTR_ID
        AND CLINICAL_EVENT.EVENT_CLASS_CD = 158 -- MED
        AND PATIENTS.PERSON_ID = CLINICAL_EVENT.PERSON_ID
        AND CLINICAL_EVENT.EVENT_CD IN (
            37556849, -- EPINephrine
            37557691, -- norepinephrine
            37557816, -- phenylephrine
            37558323, -- vasopressin
            37558389 -- DOPamine
        )
        AND CLINICAL_EVENT.EVENT_END_DT_TM < PATIENTS.REG_DT_TM + 3
        AND CLINICAL_EVENT.VALID_UNTIL_DT_TM > DATE '2099-12-31'
        AND CLINICAL_EVENT.EVENT_ID = CE_MED_RESULT.EVENT_ID
        AND CE_MED_RESULT.VALID_UNTIL_DT_TM > DATE '2099-12-31'
), VASOP_DURATION AS (
    SELECT
        ENCNTR_ID,
        MEDICATION,
        MIN(EVENT_END_DT_TM) AS VASOP_START_DT_TM,
        MAX(EVENT_END_DT_TM) - MIN(EVENT_END_DT_TM) AS VASOP_DURATION
    FROM VASOP_MEDS
    GROUP BY
        ENCNTR_ID,
        MEDICATION
)

SELECT DISTINCT
	VASOP_DURATION.ENCNTR_ID,
	ENCNTR_ALIAS.ALIAS AS FIN,
	VASOP_DURATION.MEDICATION,
    pi_from_gmt(VASOP_DURATION.VASOP_START_DT_TM, 'America/Chicago') AS VASOP_START_DATETIME,
    VASOP_DURATION.VASOP_DURATION
FROM
	ENCNTR_ALIAS,
	VASOP_DURATION
WHERE
	VASOP_DURATION.ENCNTR_ID = ENCNTR_ALIAS.ENCNTR_ID
	AND ENCNTR_ALIAS.ENCNTR_ALIAS_TYPE_CD = 619 -- FIN NBR
	AND ENCNTR_ALIAS.ACTIVE_IND = 1