WITH PATIENTS AS (
	SELECT DISTINCT
		ENCOUNTER.ENCNTR_ID,
		ENCOUNTER.PERSON_ID,
		ENCOUNTER.REG_DT_TM
	FROM
		DIAGNOSIS,
		ENCOUNTER,
		NOMENCLATURE,
		PERSON
	WHERE
		ENCOUNTER.ORGANIZATION_ID = 1 -- Memorial Hermann Hospital
		AND ENCOUNTER.REG_DT_TM BETWEEN 
			pi_to_gmt(
				TO_DATE(
					@Prompt('Enter begin date', 'D', , mono, free, persistent, {'07/01/2017 00:00:00'}, User:0), 
					pi_get_dm_info_char_gen('Date Format Mask|FT','PI EXP|Systems Configuration|Date Format Mask')
				), 
				pi_time_zone(1, @Variable('BOUSER'))
			)
			AND pi_to_gmt(
				TO_DATE(
					@Prompt('Enter end date', 'D', , mono, free, persistent, {'08/01/2021 00:00:00'}, User:1), 
					pi_get_dm_info_char_gen('Date Format Mask|FT','PI EXP|Systems Configuration|Date Format Mask')
				) - 1/86400, 
				pi_time_zone(1, @Variable('BOUSER'))
			)
		AND ENCOUNTER.LOC_FACILITY_CD = 3310 -- HH HERMANN
		-- AND ENCOUNTER.ADMIT_SRC_CD = 9061 -- Emergency Room
		AND ENCOUNTER.ENCNTR_ID = DIAGNOSIS.ENCNTR_ID
		AND DIAGNOSIS.DIAG_TYPE_CD = 26244 -- Final
		AND DIAGNOSIS.DIAG_PRIORITY = 1
		AND DIAGNOSIS.NOMENCLATURE_ID = NOMENCLATURE.NOMENCLATURE_ID
		AND REGEXP_INSTR(NOMENCLATURE.SOURCE_IDENTIFIER, '^I61') > 0
		AND NOMENCLATURE.SOURCE_VOCABULARY_CD = 641836527 -- ICD-10-CM
		AND NOMENCLATURE.PRINCIPLE_TYPE_CD = 751 -- Disease or Syndrome
		AND ENCOUNTER.PERSON_ID = PERSON.PERSON_ID
		AND TRUNC((TRUNC(pi_from_gmt(ENCOUNTER.REG_DT_TM, 'America/Chicago')) - TRUNC(pi_from_gmt(PERSON.BIRTH_DT_TM, 'America/Chicago'))) / 365.25, 0) >= 18
), TFR_FACILITY AS (
	SELECT DISTINCT
		PATIENTS.ENCNTR_ID,
		ENCOUNTER.ENCNTR_ID AS TFR_ENCNTR_ID,
		pi_get_cv_display(ENCOUNTER.LOC_FACILITY_CD) AS TFR_FACILITY,
		pi_get_cv_display(ENCOUNTER.ENCNTR_TYPE_CLASS_CD) AS TFR_ENCNTR_TYPE
	FROM
		ENCOUNTER,
		PATIENTS
	WHERE
		PATIENTS.PERSON_ID = ENCOUNTER.PERSON_ID
		AND ENCOUNTER.DISCH_DT_TM BETWEEN PATIENTS.REG_DT_TM - 1 AND PATIENTS.REG_DT_TM
		AND ENCOUNTER.ENCNTR_TYPE_CLASS_CD IN (
			42631, -- Inpatient
			55851, -- Emergency
			688523 -- Observation
		)
), PREGNANT AS (
	SELECT DISTINCT
		CLINICAL_EVENT.ENCNTR_ID,
		CLINICAL_EVENT.RESULT_VAL AS PREGNANT
		-- 'TRUE' AS PREGNANT
	FROM
		CLINICAL_EVENT,
		PATIENTS
	WHERE
		PATIENTS.ENCNTR_ID = CLINICAL_EVENT.ENCNTR_ID
		AND PATIENTS.PERSON_ID = CLINICAL_EVENT.PERSON_ID
		AND CLINICAL_EVENT.EVENT_CD IN (
			33325, -- S Preg
			34136 -- U Preg
		)
		AND CLINICAL_EVENT.RESULT_VAL <> 'Negative'
		AND CLINICAL_EVENT.VALID_UNTIL_DT_TM > DATE '2099-12-31'	
), SBP AS (
    SELECT DISTINCT
        PATIENTS.ENCNTR_ID,
        TO_NUMBER(CLINICAL_EVENT.RESULT_VAL) AS RESULT_VAL       
    FROM
        CLINICAL_EVENT,
        PATIENTS
    WHERE
        PATIENTS.ENCNTR_ID = CLINICAL_EVENT.ENCNTR_ID
        AND CLINICAL_EVENT.EVENT_CLASS_CD = 159 -- NUM
        AND PATIENTS.PERSON_ID = CLINICAL_EVENT.PERSON_ID
        AND CLINICAL_EVENT.EVENT_CD IN (
            30098, -- Systolic Blood Pressure
            134401648 -- Arterial Systolic BP 1
        )
        AND CLINICAL_EVENT.EVENT_END_DT_TM < PATIENTS.REG_DT_TM + 0.25
        AND CLINICAL_EVENT.VALID_UNTIL_DT_TM > DATE '2099-12-31'
), SBP_MIN AS (
	SELECT
		ENCNTR_ID,
		MIN(RESULT_VAL) AS MIN_SBP
	FROM SBP
	WHERE RESULT_VAL >= 40
    GROUP BY ENCNTR_ID
)

SELECT DISTINCT
	PATIENTS.ENCNTR_ID,
	ENCNTR_ALIAS.ALIAS AS FIN,
	ENCOUNTER.DISCH_DT_TM - ENCOUNTER.REG_DT_TM AS LOS,	
	pi_get_cv_display(ENCOUNTER.ADMIT_SRC_CD) AS ADMIT_SRC,
	TFR_FACILITY.TFR_FACILITY,
	pi_get_cv_display(ENCOUNTER.DISCH_DISPOSITION_CD) AS DISCH_DISPOSITION,
    PREGNANT.PREGNANT,
	SBP_MIN.MIN_SBP
FROM
	ENCNTR_ALIAS,
	ENCOUNTER,
	PATIENTS,
    PREGNANT,
    SBP_MIN,
	TFR_FACILITY
WHERE
	PATIENTS.ENCNTR_ID = ENCOUNTER.ENCNTR_ID
	AND PATIENTS.ENCNTR_ID = TFR_FACILITY.ENCNTR_ID(+)
    AND PATIENTS.ENCNTR_ID = PREGNANT.ENCNTR_ID(+)
    AND PATIENTS.ENCNTR_ID = SBP_MIN.ENCNTR_ID(+)
	AND PATIENTS.ENCNTR_ID = ENCNTR_ALIAS.ENCNTR_ID
	AND ENCNTR_ALIAS.ENCNTR_ALIAS_TYPE_CD = 619 -- FIN NBR
	AND ENCNTR_ALIAS.ACTIVE_IND = 1	
