WITH PATIENTS AS (
	SELECT DISTINCT
		ENCOUNTER.ENCNTR_ID,
		ENCOUNTER.PERSON_ID,
		ENCNTR_ALIAS.ALIAS AS FIN,
		ENCOUNTER.ARRIVE_DT_TM,
		ENCOUNTER.REG_DT_TM
	FROM
		ENCNTR_ALIAS,
		ENCOUNTER
	WHERE
	    ENCNTR_ALIAS.ALIAS IN @prompt('Enter value(s) for Alias','A',,Multi,Free,Persistent,,User:0)
		AND ENCNTR_ALIAS.ENCNTR_ALIAS_TYPE_CD = 619 -- FIN NBR
		AND ENCNTR_ALIAS.ACTIVE_IND = 1
		AND ENCNTR_ALIAS.ENCNTR_ID = ENCOUNTER.ENCNTR_ID
), TFR_FACILITY AS (
	SELECT DISTINCT
		PATIENTS.ENCNTR_ID,
		PATIENTS.PERSON_ID,
		ENCOUNTER.ENCNTR_ID AS TFR_ENCNTR_ID
	FROM
		ENCOUNTER,
		PATIENTS
	WHERE
		PATIENTS.PERSON_ID = ENCOUNTER.PERSON_ID
		AND ENCOUNTER.DISCH_DT_TM BETWEEN PATIENTS.REG_DT_TM - 1 AND PATIENTS.REG_DT_TM
		AND ENCOUNTER.ENCNTR_TYPE_CLASS_CD IN (
			42631, -- Inpatient
			55851, -- Emergency
			688523 -- Observation
		)
), ENCNTR_LIST AS (
	SELECT ENCNTR_ID FROM PATIENTS
	UNION
	SELECT TFR_ENCNTR_ID AS ENCNTR_ID FROM TFR_FACILITY
), RAD_ORDERS AS (
    SELECT DISTINCT
        PATIENTS.ENCNTR_ID,
        ORDER_RADIOLOGY.ORDER_ID,
        pi_get_cv_display(ORDER_RADIOLOGY.CATALOG_CD) AS CATALOG
    FROM 
        ORDER_RADIOLOGY,
        PATIENTS
    WHERE 
        PATIENTS.PERSON_ID = ORDER_RADIOLOGY.PERSON_ID
		AND ORDER_RADIOLOGY.ENCNTR_ID IN (SELECT DISTINCT ENCNTR_ID FROM ENCNTR_LIST)
        AND ORDER_RADIOLOGY.EXAM_STATUS_CD = 2442 -- Completed
		AND ORDER_RADIOLOGY.START_DT_TM 
)

SELECT DISTINCT
	-- PATIENTS.ENCNTR_ID,
	PATIENTS.FIN,
    RAD_ORDERS.ORDER_ID,
	TO_CHAR(pi_from_gmt(CLINICAL_EVENT.EVENT_END_DT_TM, 'America/Chicago'), 'YYYY-MM-DD"T"HH24:MI:SS') AS EVENT_DATETIME,	
    CLINICAL_EVENT.EVENT_ID,
    pi_get_cv_display(CLINICAL_EVENT.EVENT_CD) AS EVENT
FROM 
    CLINICAL_EVENT,
	PATIENTS,
    RAD_ORDERS
WHERE 
	PATIENTS.ENCNTR_ID = RAD_ORDERS.ENCNTR_ID
	AND RAD_ORDERS.ORDER_ID = CLINICAL_EVENT.ORDER_ID
    AND CLINICAL_EVENT.VALID_UNTIL_DT_TM > DATE '2099-12-31'