WITH PATIENTS AS (
	SELECT DISTINCT
		ENCOUNTER.ENCNTR_ID,
		ENCOUNTER.PERSON_ID,
		ENCNTR_ALIAS.ALIAS AS FIN
	FROM
		ENCNTR_ALIAS,
		ENCOUNTER
	WHERE
	    ENCNTR_ALIAS.ALIAS IN @prompt('Enter value(s) for Alias','A',,Multi,Free,Persistent,,User:0)
		AND ENCNTR_ALIAS.ENCNTR_ALIAS_TYPE_CD = 619 -- FIN NBR
		AND ENCNTR_ALIAS.ACTIVE_IND = 1
		AND ENCNTR_ALIAS.ENCNTR_ID = ENCOUNTER.ENCNTR_ID
)

SELECT DISTINCT
	PATIENTS.FIN,
	TO_CHAR(pi_from_gmt(SURGICAL_CASE.SURG_START_DT_TM, (pi_time_zone(1, @Variable('BOUSER')))), 'YYYY-MM-DD"T"HH24:MI:SS') AS SURGERY_START_DATETIME,
	TO_CHAR(pi_from_gmt(SURGICAL_CASE.SURG_STOP_DT_TM, (pi_time_zone(1, @Variable('BOUSER')))), 'YYYY-MM-DD"T"HH24:MI:SS') AS SURGERY_STOP_DATETIME,
	CASE SURG_CASE_PROCEDURE.PRIMARY_PROC_IND
		WHEN 1 THEN 'TRUE'
		ELSE 'FALSE'
	END AS PRIMARY_PROCEDURE,
    SURG_CASE_PROCEDURE.SURG_PROC_CD,
	pi_get_cv_display(SURG_CASE_PROCEDURE.SURG_PROC_CD) AS SURGERY
FROM
	PATIENTS,
	SURGICAL_CASE,
	SURG_CASE_PROCEDURE
WHERE
    PATIENTS.ENCNTR_ID = SURGICAL_CASE.ENCNTR_ID
    AND SURGICAL_CASE.ACTIVE_IND = 1
    AND SURGICAL_CASE.SURG_AREA_CD > 0
	AND SURGICAL_CASE.SURG_CASE_ID = SURG_CASE_PROCEDURE.SURG_CASE_ID
    AND SURG_CASE_PROCEDURE.ACTIVE_IND = 1
