WITH PATIENTS AS (
	SELECT DISTINCT
		ENCOUNTER.ENCNTR_ID,
		ENCOUNTER.PERSON_ID,
		ENCNTR_ALIAS.ALIAS AS FIN
	FROM
		ENCNTR_ALIAS,
		ENCOUNTER
	WHERE
	    ENCNTR_ALIAS.ALIAS IN @prompt('Enter value(s) for Alias','A',,Multi,Free,Persistent,,User:0)
		AND ENCNTR_ALIAS.ENCNTR_ALIAS_TYPE_CD = 619 -- FIN NBR
		AND ENCNTR_ALIAS.ACTIVE_IND = 1
		AND ENCNTR_ALIAS.ENCNTR_ID = ENCOUNTER.ENCNTR_ID
)

SELECT DISTINCT
    PATIENTS.ENCNTR_ID,
	PATIENTS.FIN,
	DIAGNOSIS.DIAG_PRIORITY,
    NOMENCLATURE.SOURCE_IDENTIFIER AS ICD_10_CODE,
    NOMENCLATURE.SOURCE_STRING AS ICD_10_DESCRIPTION
FROM
    DIAGNOSIS,
    NOMENCLATURE,
    PATIENTS
WHERE
    PATIENTS.ENCNTR_ID = DIAGNOSIS.ENCNTR_ID
    AND DIAGNOSIS.DIAG_TYPE_CD = 26244 -- Final
    AND DIAGNOSIS.NOMENCLATURE_ID = NOMENCLATURE.NOMENCLATURE_ID
    -- AND REGEXP_INSTR(NOMENCLATURE.SOURCE_IDENTIFIER, '^E08|^E10|^E78|^I63|^I68|^F17.2|^I48|^I61.5|^I46') > 0 
    AND NOMENCLATURE.SOURCE_VOCABULARY_CD = 641836527 -- ICD-10-CM
    AND NOMENCLATURE.PRINCIPLE_TYPE_CD = 751 -- Disease or Syndrome
    