WITH PATIENTS AS (
	SELECT DISTINCT
		ENCOUNTER.ENCNTR_ID,
		ENCOUNTER.PERSON_ID,
		ENCNTR_ALIAS.ALIAS AS FIN,
		ENCOUNTER.DISCH_DT_TM
	FROM
		ENCNTR_ALIAS,
		ENCOUNTER
	WHERE
	    ENCNTR_ALIAS.ALIAS IN @prompt('Enter value(s) for Alias','A',,Multi,Free,Persistent,,User:0)
		AND ENCNTR_ALIAS.ENCNTR_ALIAS_TYPE_CD = 619 -- FIN NBR
		AND ENCNTR_ALIAS.ACTIVE_IND = 1
		AND ENCNTR_ALIAS.ENCNTR_ID = ENCOUNTER.ENCNTR_ID
), UNIT_LIST AS (
	SELECT DISTINCT
		ENCNTR_LOC_HIST.ENCNTR_ID,
		pi_from_gmt(ENCNTR_LOC_HIST.BEG_EFFECTIVE_DT_TM, 'America/Chicago') AS BEGIN_DATETIME,
        pi_from_gmt(ENCNTR_LOC_HIST.END_EFFECTIVE_DT_TM, 'America/Chicago') AS END_DATETIME,
        pi_from_gmt(ENCNTR_LOC_HIST.TRANSACTION_DT_TM, 'America/Chicago') AS TRANSACT_DATETIME,
		pi_get_cv_display(ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD) AS NURSE_UNIT,
		LEAST(ENCNTR_LOC_HIST.END_EFFECTIVE_DT_TM, PATIENTS.DISCH_DT_TM) - ENCNTR_LOC_HIST.BEG_EFFECTIVE_DT_TM AS TRANSACTION_DURATION
	FROM
		ENCNTR_LOC_HIST,
	    PATIENTS
	WHERE
		PATIENTS.ENCNTR_ID = ENCNTR_LOC_HIST.ENCNTR_ID
		AND PATIENTS.DISCH_DT_TM >= ENCNTR_LOC_HIST.BEG_EFFECTIVE_DT_TM
        AND ENCNTR_LOC_HIST.ACTIVE_IND = 1
), UNIT_IN_OUT AS (
    SELECT DISTINCT
        UNIT_LIST.*,
		CASE
			WHEN LAG(NURSE_UNIT, 1, 0) OVER (PARTITION BY ENCNTR_ID ORDER BY BEGIN_DATETIME) <> NURSE_UNIT THEN 1
			ELSE 0
		END AS UNIT_IN
    FROM
        UNIT_LIST
	WHERE
	    TRANSACTION_DURATION >= (1 / 60 / 24)
), UNIT_COUNT AS (
	SELECT DISTINCT
	    UNIT_IN_OUT.*,
		SUM(UNIT_IN) OVER (PARTITION BY ENCNTR_ID ORDER BY BEGIN_DATETIME) AS UNIT_COUNT
	FROM
		UNIT_IN_OUT
), UNIT_LOS AS (
	SELECT
		ENCNTR_ID,
		UNIT_COUNT,
		NURSE_UNIT,
		MIN(BEGIN_DATETIME) AS UNIT_IN_DATETIME,
		MAX(END_DATETIME) AS UNIT_OUT_DATETIME,
		SUM(TRANSACTION_DURATION) AS UNIT_LOS
	FROM
		UNIT_COUNT
	GROUP BY
		ENCNTR_ID,
		UNIT_COUNT,
		NURSE_UNIT
)

SELECT DISTINCT
	PATIENTS.ENCNTR_ID,
	PATIENTS.FIN,
	UNIT_LOS.UNIT_COUNT,
	UNIT_LOS.NURSE_UNIT,
	UNIT_LOS.UNIT_LOS,
	UNIT_LOS.UNIT_IN_DATETIME,
	UNIT_LOS.UNIT_OUT_DATETIME
FROM
	PATIENTS,
	UNIT_LOS
WHERE
	PATIENTS.ENCNTR_ID = UNIT_LOS.ENCNTR_ID
		