WITH PATIENTS AS (
	SELECT DISTINCT
		ENCOUNTER.ENCNTR_ID,
		ENCOUNTER.PERSON_ID,
		-- pi_get_cv_display(ENCOUNTER.LOC_FACILITY_CD) AS FACILITY,
		ENCOUNTER.ARRIVE_DT_TM,
		ENCOUNTER.REG_DT_TM,
		ENCOUNTER.DISCH_DT_TM
		-- ENCOUNTER.ADMIT_SRC_CD,
		-- pi_get_cv_display(ENCOUNTER.ADMIT_SRC_CD) AS ADMIT_SRC
		-- pi_get_cv_display(ENCOUNTER.DISCH_DISPOSITION_CD) AS DISCH_DISPOSITION
	FROM
		-- DIAGNOSIS,
		ENCOUNTER,
		NOMENCLATURE,
		PERSON,
		PROCEDURE
	WHERE
		ENCOUNTER.ORGANIZATION_ID = 1 -- Memorial Hermann Hospital
		AND ENCOUNTER.REG_DT_TM BETWEEN 
			pi_to_gmt(
				TO_DATE(
					@Prompt('Enter begin date', 'D', , mono, free, persistent, {'07/01/2017 00:00:00'}, User:0), 
					pi_get_dm_info_char_gen('Date Format Mask|FT','PI EXP|Systems Configuration|Date Format Mask')
				), 
				pi_time_zone(1, @Variable('BOUSER'))
			)
			AND pi_to_gmt(
				TO_DATE(
					@Prompt('Enter end date', 'D', , mono, free, persistent, {'07/01/2024 00:00:00'}, User:1), 
					pi_get_dm_info_char_gen('Date Format Mask|FT','PI EXP|Systems Configuration|Date Format Mask')
				) - 1/86400, 
				pi_time_zone(1, @Variable('BOUSER'))
			)
		AND ENCOUNTER.LOC_FACILITY_CD = 3310 -- HH HERMANN
		-- AND ENCOUNTER.ADMIT_SRC_CD = 9061 -- Emergency Room
		-- AND ENCOUNTER.ENCNTR_ID = DIAGNOSIS.ENCNTR_ID
		-- AND DIAGNOSIS.DIAG_TYPE_CD = 26244 -- Final
		-- AND DIAGNOSIS.DIAG_PRIORITY = 1
		AND ENCOUNTER.ENCNTR_ID = PROCEDURE.ENCNTR_ID
		AND PROCEDURE.NOMENCLATURE_ID = NOMENCLATURE.NOMENCLATURE_ID 
		-- AND DIAGNOSIS.NOMENCLATURE_ID = NOMENCLATURE.NOMENCLATURE_ID
		AND REGEXP_INSTR(NOMENCLATURE.SOURCE_IDENTIFIER, '^037[G-N]') > 0
		AND NOMENCLATURE.SOURCE_VOCABULARY_CD = 641836522 -- ICD-10-PCS
		AND NOMENCLATURE.PRINCIPLE_TYPE_CD = 761 -- Procedure
		-- AND NOMENCLATURE.SOURCE_VOCABULARY_CD = 641836527 -- ICD-10-CM
		-- AND NOMENCLATURE.PRINCIPLE_TYPE_CD = 751 -- Disease or Syndrome
		AND ENCOUNTER.PERSON_ID = PERSON.PERSON_ID
		AND TRUNC((TRUNC(pi_from_gmt(ENCOUNTER.REG_DT_TM, 'America/Chicago')) - TRUNC(pi_from_gmt(PERSON.BIRTH_DT_TM, 'America/Chicago'))) / 365.25, 0) >= 18
), DOSES AS (
	SELECT DISTINCT
		PATIENTS.ENCNTR_ID,
		pi_get_cv_display(CLINICAL_EVENT.EVENT_CD) AS MEDICATION,
		MIN(pi_from_gmt(CLINICAL_EVENT.EVENT_END_DT_TM, 'America/Chicago')) AS MED_DATETIME
		-- CLINICAL_EVENT.EVENT_ID,
	FROM
		CE_MED_RESULT,
		CLINICAL_EVENT,
		PATIENTS
	WHERE
		PATIENTS.ENCNTR_ID = CLINICAL_EVENT.ENCNTR_ID
		AND CLINICAL_EVENT.EVENT_CLASS_CD = 158 -- MED
		AND PATIENTS.PERSON_ID = CLINICAL_EVENT.PERSON_ID
		AND CLINICAL_EVENT.EVENT_CD IN (
			37556189, -- aspirin
			37556579, -- clopidogrel
			37556867 -- eptifibatide
		)
		AND CLINICAL_EVENT.VALID_UNTIL_DT_TM > DATE '2099-12-31'
		AND CLINICAL_EVENT.EVENT_ID = CE_MED_RESULT.EVENT_ID
		AND CE_MED_RESULT.VALID_UNTIL_DT_TM > DATE '2099-12-31'
	GROUP BY
		PATIENTS.ENCNTR_ID,
		CLINICAL_EVENT.EVENT_CD
), MEDS_PIVOT AS (
	SELECT * FROM DOSES
	PIVOT(
		MIN(MED_DATETIME) FOR MEDICATION IN (
			'aspirin' AS ASPIRIN,
			'clopidogrel' AS CLOPIDOGREL,
			'eptifibatide' AS EPTIFIBATIDE
		)
	)
), LABS AS (
	SELECT DISTINCT
		PATIENTS.ENCNTR_ID,
		MIN(pi_from_gmt(CLINICAL_EVENT.EVENT_END_DT_TM, 'America/Chicago')) AS LAB_DATETIME,
		MIN(CLINICAL_EVENT.RESULT_VAL) KEEP (DENSE_RANK FIRST ORDER BY CLINICAL_EVENT.EVENT_END_DT_TM, CLINICAL_EVENT.EVENT_ID) AS PLAVIX_EFFECT_PLT
	FROM
		CLINICAL_EVENT,
		PATIENTS
	WHERE
		PATIENTS.ENCNTR_ID = CLINICAL_EVENT.ENCNTR_ID
		AND CLINICAL_EVENT.EVENT_CLASS_CD = 159 -- NUM
		AND PATIENTS.PERSON_ID = CLINICAL_EVENT.PERSON_ID
		AND CLINICAL_EVENT.EVENT_CD IN (
			1640434193, -- Plavix Effect Platelet
			219271888 -- Plav Effect Plt
		)
		AND CLINICAL_EVENT.VALID_UNTIL_DT_TM > DATE '2099-12-31'
	GROUP BY
		PATIENTS.ENCNTR_ID
)

SELECT DISTINCT
	ENCNTR_ALIAS.ALIAS AS FIN,
	PATIENTS.ENCNTR_ID,
	pi_from_gmt(PATIENTS.REG_DT_TM, 'America/Chicago') AS ADMIT_DATETIME,
	MEDS_PIVOT.ASPIRIN,
	MEDS_PIVOT.CLOPIDOGREL,
	MEDS_PIVOT.EPTIFIBATIDE,
	LABS.LAB_DATETIME,
	LABS.PLAVIX_EFFECT_PLT
FROM
	ENCNTR_ALIAS,
	LABS,
	MEDS_PIVOT,
	PATIENTS
WHERE
	PATIENTS.ENCNTR_ID = MEDS_PIVOT.ENCNTR_ID
	AND (
		(MEDS_PIVOT.ASPIRIN IS NOT NULL AND MEDS_PIVOT.CLOPIDOGREL IS NOT NULL)
		OR MEDS_PIVOT.EPTIFIBATIDE IS NOT NULL
	)
	AND PATIENTS.ENCNTR_ID = LABS.ENCNTR_ID(+)
	AND PATIENTS.ENCNTR_ID = ENCNTR_ALIAS.ENCNTR_ID
	AND ENCNTR_ALIAS.ENCNTR_ALIAS_TYPE_CD = 619 -- FIN NBR
	AND ENCNTR_ALIAS.ACTIVE_IND = 1	
	