WITH PATIENTS AS (
	SELECT DISTINCT
		CLINICAL_EVENT.ENCNTR_ID,
		CLINICAL_EVENT.PERSON_ID,
		CASE
			WHEN ORDERS.TEMPLATE_ORDER_ID = 0 THEN ORDERS.ORDER_ID
			ELSE ORDERS.TEMPLATE_ORDER_ID
		END AS ORIG_ORDER_ID,
		CLINICAL_EVENT.EVENT_END_DT_TM,
		CLINICAL_EVENT.EVENT_ID,
		CE_MED_RESULT.ADMIN_DOSAGE
	FROM 
		CE_MED_RESULT,
		CLINICAL_EVENT,
		ENCNTR_LOC_HIST,
		ORDERS
	WHERE
		CLINICAL_EVENT.EVENT_CD = 37557998 -- rocuronium
		AND CLINICAL_EVENT.EVENT_END_DT_TM BETWEEN
            pi_to_gmt(
                TO_DATE(
                    @Prompt('Enter begin date', 'D', , mono, free, persistent, {'07/01/2017 00:00:00'}, User:0), 
                    pi_get_dm_info_char_gen('Date Format Mask|FT','PI EXP|Systems Configuration|Date Format Mask')
                ), 
                pi_time_zone(1, 'America/Chicago')
            )
            AND pi_to_gmt(
                TO_DATE(
                    @Prompt('Enter end date', 'D', , mono, free, persistent, {'07/01/2022 00:00:00'}, User:1), 
                    pi_get_dm_info_char_gen('Date Format Mask|FT','PI EXP|Systems Configuration|Date Format Mask')
                ) - 1/86400, 
                pi_time_zone(1, 'America/Chicago')
            )	
		AND CLINICAL_EVENT.VALID_UNTIL_DT_TM > DATE '2099-12-31'
		AND CLINICAL_EVENT.EVENT_ID = CE_MED_RESULT.EVENT_ID
		AND CE_MED_RESULT.ADMIN_DOSAGE > 0
		AND CE_MED_RESULT.IV_EVENT_CD = 0
		AND CE_MED_RESULT.VALID_UNTIL_DT_TM > DATE '2099-12-31'
		AND CLINICAL_EVENT.ENCNTR_ID = ENCNTR_LOC_HIST.ENCNTR_ID
		AND ENCNTR_LOC_HIST.BEG_EFFECTIVE_DT_TM <= CLINICAL_EVENT.EVENT_END_DT_TM
		AND ENCNTR_LOC_HIST.TRANSACTION_DT_TM = (
			SELECT MAX(ELH.TRANSACTION_DT_TM)
			FROM ENCNTR_LOC_HIST ELH
			WHERE
				CLINICAL_EVENT.ENCNTR_ID = ELH.ENCNTR_ID
				AND ELH.TRANSACTION_DT_TM <= CLINICAL_EVENT.EVENT_END_DT_TM
				AND ELH.ACTIVE_IND = 1
		)
		AND ENCNTR_LOC_HIST.END_EFFECTIVE_DT_TM >= CLINICAL_EVENT.EVENT_END_DT_TM
		AND ENCNTR_LOC_HIST.ACTIVE_IND = 1   
		AND ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD IN (
			4122, -- HH MICU
			4137, -- HH CCU
			5441, -- HH STIC
			5541, -- HH CVICU
			18116572, -- HH 8WJP
			283905037, -- HH 7J
			1993318732, -- HH HFIC
			2369096643, -- HH TSCU
			2041371668, -- HH NVIC
			3311213379, -- HH TICU
			3224987721, -- HH S STIC
			3224986803, -- HH S BURN
			3224988589, -- HH S SHIC
			3224988925, -- HH S TSIC
			3392290381, -- HH S MICU
			277570335, -- HH EDHH
			277573736, -- HH EDTR
			277567038, -- HH VUHH
			508618957, -- HH EREV
			3224989205, -- HH S VUHH
			3224989653, -- HH S EDHH
			3224990761, -- HH S EDTR
			3224990803 -- HH S EREV
		)
		AND CLINICAL_EVENT.ORDER_ID = ORDERS.ORDER_ID
), SURG_TIMES AS (
	SELECT DISTINCT
		PATIENTS.ENCNTR_ID,
		SURGICAL_CASE.SURG_CASE_ID,
		SURGICAL_CASE.SURG_START_DT_TM,
		SURGICAL_CASE.SURG_STOP_DT_TM,
		CT_ANESTH_START.CASE_TIME_DT_TM AS ANESTH_START_DT_TM,
		CT_ANESTH_STOP.CASE_TIME_DT_TM AS ANESTH_STOP_DT_TM
	FROM
		CASE_TIMES CT_ANESTH_START,
		CASE_TIMES CT_ANESTH_STOP,
		PATIENTS,
		SURGICAL_CASE
	WHERE
		PATIENTS.ENCNTR_ID = SURGICAL_CASE.ENCNTR_ID
		AND SURGICAL_CASE.SURG_CASE_ID = CT_ANESTH_START.SURG_CASE_ID
		AND CT_ANESTH_START.TASK_ASSAY_CD = 10511932 -- SN - CTm - Anesthesia - Start Time
		AND SURGICAL_CASE.SURG_CASE_ID = CT_ANESTH_STOP.SURG_CASE_ID
		AND CT_ANESTH_STOP.TASK_ASSAY_CD = 10511933 -- SN - CTm - Anesthesia - Stop Time
), OR_DOSES AS (
	SELECT 
		PATIENTS.*, 
		SURG_TIMES.SURG_CASE_ID,
		SURG_TIMES.ANESTH_START_DT_TM, 
		SURG_TIMES.ANESTH_STOP_DT_TM,
		CASE
			WHEN PATIENTS.EVENT_END_DT_TM BETWEEN SURG_TIMES.ANESTH_START_DT_TM AND SURG_TIMES.ANESTH_STOP_DT_TM THEN 1
			ELSE 0
		END AS OR_DOSE
	FROM 
		PATIENTS,
		SURG_TIMES
	WHERE 
		PATIENTS.ENCNTR_ID = SURG_TIMES.ENCNTR_ID(+)
), DOSES AS (
	SELECT
		ENCNTR_ID,
		PERSON_ID,
		ORIG_ORDER_ID,
		EVENT_END_DT_TM,
		EVENT_ID,
		ADMIN_DOSAGE,
		MAX(OR_DOSE) AS OR_DOSE
	FROM
		OR_DOSES
	GROUP BY
		ENCNTR_ID,
		PERSON_ID,
		ORIG_ORDER_ID,
		EVENT_END_DT_TM,
		EVENT_ID,
		ADMIN_DOSAGE
), DOSE_WT AS (
	SELECT DISTINCT
		DOSES.*,
		ORDER_DETAIL.OE_FIELD_DISPLAY_VALUE AS ORDER_WEIGHT
	FROM
		DOSES,
		ORDER_DETAIL
	WHERE
		DOSES.OR_DOSE = 0
		AND DOSES.ORIG_ORDER_ID = ORDER_DETAIL.ORDER_ID(+)
		AND ORDER_DETAIL.OE_FIELD_MEANING_ID(+) = 99 -- WEIGHT
), WEIGHTS AS (
	SELECT DISTINCT
		DOSE_WT.ENCNTR_ID,
		DOSE_WT.ORIG_ORDER_ID,
		DOSE_WT.EVENT_END_DT_TM,
		MIN(CLINICAL_EVENT.RESULT_VAL) KEEP (DENSE_RANK LAST ORDER BY CLINICAL_EVENT.EVENT_END_DT_TM, CLINICAL_EVENT.EVENT_ID) AS WEIGHT_KG
	FROM
		CLINICAL_EVENT,
		DOSE_WT
	WHERE
		DOSE_WT.ENCNTR_ID = CLINICAL_EVENT.ENCNTR_ID
		AND CLINICAL_EVENT.EVENT_CLASS_CD = 159 -- NUM
		AND DOSE_WT.PERSON_ID = CLINICAL_EVENT.PERSON_ID
		AND CLINICAL_EVENT.EVENT_CD = 30107 -- Weight
		AND CLINICAL_EVENT.EVENT_END_DT_TM < DOSE_WT.EVENT_END_DT_TM
		AND CLINICAL_EVENT.VALID_UNTIL_DT_TM > DATE '2099-12-31'
		AND CLINICAL_EVENT.RESULT_UNITS_CD = 170 -- kg
	GROUP BY
		DOSE_WT.ENCNTR_ID,
		DOSE_WT.ORIG_ORDER_ID,
		DOSE_WT.EVENT_END_DT_TM
), ROC_DOSES AS (
	SELECT DISTINCT
		DOSE_WT.*,
		TO_NUMBER(WEIGHTS.WEIGHT_KG) AS WEIGHT,
		ADMIN_DOSAGE / TO_NUMBER(COALESCE(ORDER_WEIGHT, WEIGHT_KG)) AS DOSE_MG_KG
	FROM
		DOSE_WT,
		WEIGHTS
	WHERE
		DOSE_WT.ENCNTR_ID = WEIGHTS.ENCNTR_ID(+)
		AND DOSE_WT.ORIG_ORDER_ID = WEIGHTS.ORIG_ORDER_ID(+)
		AND DOSE_WT.EVENT_END_DT_TM = WEIGHTS.EVENT_END_DT_TM(+)
), ROC_MAX AS (
	SELECT
		ENCNTR_ID,
		MAX(ORDER_WEIGHT) AS ORDER_WEIGHT,
		MAX(WEIGHT) AS WEIGHT,
		MAX(ADMIN_DOSAGE) AS MAX_DOSE,
		MAX(DOSE_MG_KG) AS DOSE_MG_KG
	FROM
		ROC_DOSES
	GROUP BY
		ENCNTR_ID
)

SELECT 
	ROC_MAX.*,
	NOMENCLATURE.SOURCE_IDENTIFIER AS ICD10_CODE,
	NOMENCLATURE.SOURCE_STRING AS ICD10_DESC
FROM
	DIAGNOSIS,
	NOMENCLATURE,
	ROC_MAX
WHERE
	ROC_MAX.ENCNTR_ID = DIAGNOSIS.ENCNTR_ID
	AND DIAGNOSIS.DIAG_TYPE_CD = 26244 -- Final
	AND DIAGNOSIS.DIAG_PRIORITY = 1
	AND DIAGNOSIS.NOMENCLATURE_ID = NOMENCLATURE.NOMENCLATURE_ID
	-- AND REGEXP_INSTR(NOMENCLATURE.SOURCE_IDENTIFIER, '^I63.6') > 0
	AND NOMENCLATURE.SOURCE_VOCABULARY_CD = 641836527 -- ICD-10-CM
	AND NOMENCLATURE.PRINCIPLE_TYPE_CD = 751 -- Disease or Syndrome
