WITH PATIENTS AS (
	SELECT DISTINCT
		ENCOUNTER.ENCNTR_ID,
		ENCOUNTER.PERSON_ID,
		ENCNTR_ALIAS.ALIAS AS FIN
	FROM
		ENCNTR_ALIAS,
		ENCOUNTER
	WHERE
	    ENCNTR_ALIAS.ALIAS IN @prompt('Enter value(s) for Alias','A',,Multi,Free,Persistent,,User:0)
		AND ENCNTR_ALIAS.ENCNTR_ALIAS_TYPE_CD = 619 -- FIN NBR
		AND ENCNTR_ALIAS.ACTIVE_IND = 1
		AND ENCNTR_ALIAS.ENCNTR_ID = ENCOUNTER.ENCNTR_ID
)

SELECT DISTINCT
    PATIENTS.ENCNTR_ID,
	PATIENTS.FIN,
    NOMENCLATURE.SOURCE_IDENTIFIER AS ICD_10_PCS,
    NOMENCLATURE.SOURCE_STRING AS PROCEDURE
FROM
    NOMENCLATURE,
    PATIENTS,
	PROCEDURE
WHERE
    PATIENTS.ENCNTR_ID = PROCEDURE.ENCNTR_ID
	AND PROCEDURE.NOMENCLATURE_ID = NOMENCLATURE.NOMENCLATURE_ID
	AND REGEXP_INSTR(NOMENCLATURE.SOURCE_IDENTIFIER, '03CG3ZZ|037J3ZZ') > 0 
	AND NOMENCLATURE.SOURCE_VOCABULARY_CD = 641836522 -- ICD-10-PCS
	AND NOMENCLATURE.PRINCIPLE_TYPE_CD = 761 -- Procedure