WITH DOSES AS (
	SELECT DISTINCT
		CLINICAL_EVENT.ENCNTR_ID,
		CLINICAL_EVENT.PERSON_ID,
		CASE
			WHEN ORDERS.TEMPLATE_ORDER_ID = 0 THEN CLINICAL_EVENT.ORDER_ID
			ELSE ORDERS.TEMPLATE_ORDER_ID
		END AS ORIG_ORDER_ID,
		pi_from_gmt(CLINICAL_EVENT.EVENT_END_DT_TM, 'America/Chicago') AS DOSE_DATETIME,
		TRUNC(pi_from_gmt(CLINICAL_EVENT.EVENT_END_DT_TM, 'America/Chicago'), 'MONTH') AS DOSE_MONTH,
		TRUNC(ADD_MONTHS(TRUNC(pi_from_gmt(CLINICAL_EVENT.EVENT_END_DT_TM, 'America/Chicago'), 'MONTH'), 6), 'YEAR') AS FISCAL_YEAR,
		CLINICAL_EVENT.EVENT_ID,
		pi_get_cv_display(CLINICAL_EVENT.EVENT_CD) AS MEDICATION,
		pi_get_cv_display(CE_MED_RESULT.ADMIN_ROUTE_CD) AS ROUTE
	FROM
		CE_MED_RESULT,
		CLINICAL_EVENT,
		ENCNTR_LOC_HIST,
		ORDERS
	WHERE
		CLINICAL_EVENT.EVENT_CD IN (
			37556053, -- albuterol
			37556054, -- albuterol *5 mg/ml neb SOLN
			37556055, -- albuterol-ipratropium
			37556344, -- budesonide 0.25 mg/2 ml neb SOLN
			37556346, -- budesonide neb SOLN
			48069084, -- budesonide inhalation
			37556343, -- budesonide
			37557325, -- ipratropium
			37557410, -- levalbuterol
			37556036, -- acetylcysteine
			37558068 -- sodium chloride		
		)
		AND CLINICAL_EVENT.EVENT_END_DT_TM BETWEEN
			pi_to_gmt(
				TO_DATE(
					@Prompt('Enter begin date', 'D', , mono, free, persistent, {'01/01/2020 00:00:00'}, User:0), 
					pi_get_dm_info_char_gen('Date Format Mask|FT','PI EXP|Systems Configuration|Date Format Mask')
				), 
				'America/Chicago'
			)
			AND pi_to_gmt(
				TO_DATE(
					@Prompt('Enter end date', 'D', , mono, free, persistent, {'10/05/2024 00:00:00'}, User:1), 
					pi_get_dm_info_char_gen('Date Format Mask|FT','PI EXP|Systems Configuration|Date Format Mask')
				) - 1/86400, 
				'America/Chicago'
			)
		AND CLINICAL_EVENT.VALID_UNTIL_DT_TM > DATE '2099-12-31'
		AND CLINICAL_EVENT.EVENT_ID = CE_MED_RESULT.EVENT_ID
		AND CE_MED_RESULT.VALID_UNTIL_DT_TM > DATE '2099-12-31'
		AND CE_MED_RESULT.IV_EVENT_CD = 0
		AND CLINICAL_EVENT.ENCNTR_ID = ENCNTR_LOC_HIST.ENCNTR_ID
		AND ENCNTR_LOC_HIST.BEG_EFFECTIVE_DT_TM <= CLINICAL_EVENT.EVENT_END_DT_TM
		AND ENCNTR_LOC_HIST.TRANSACTION_DT_TM = (
			SELECT MAX(ELH.TRANSACTION_DT_TM)
			FROM ENCNTR_LOC_HIST ELH
			WHERE
				CLINICAL_EVENT.ENCNTR_ID = ELH.ENCNTR_ID
				AND ELH.ACTIVE_IND = 1
				AND ELH.TRANSACTION_DT_TM <= CLINICAL_EVENT.EVENT_END_DT_TM
		)
		AND ENCNTR_LOC_HIST.END_EFFECTIVE_DT_TM >= CLINICAL_EVENT.EVENT_END_DT_TM
		AND ENCNTR_LOC_HIST.ACTIVE_IND = 1
		AND ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD = 283905037 -- HH 7J
		AND CLINICAL_EVENT.ORDER_ID = ORDERS.ORDER_ID
), PRODS AS (
	SELECT DISTINCT
		DOSES.*,
		MED_IDENTIFIER.VALUE AS MED_PRODUCT
	FROM
		DOSES,
		MED_IDENTIFIER,
		ORDER_PRODUCT
	WHERE
		DOSES.ORIG_ORDER_ID = ORDER_PRODUCT.ORDER_ID
		AND ORDER_PRODUCT.ITEM_ID = MED_IDENTIFIER.ITEM_ID
		AND MED_IDENTIFIER.MED_IDENTIFIER_TYPE_CD = 1564 -- Description
		AND MED_IDENTIFIER.MED_PRODUCT_ID = 0 
		AND DOSES.ROUTE = 'NEB'
)

SELECT
	MED_PRODUCT,
	FISCAL_YEAR,
	ROUTE,
	COUNT(DISTINCT EVENT_ID) AS NUM_DOSES
FROM
	PRODS
GROUP BY
	MED_PRODUCT,
	FISCAL_YEAR,
	ROUTE