WITH DOSES AS (
	SELECT DISTINCT
		CLINICAL_EVENT.ENCNTR_ID,
		CLINICAL_EVENT.PERSON_ID,
		CASE
			WHEN ORDERS.TEMPLATE_ORDER_ID = 0 THEN ORDERS.ORDER_ID
			ELSE ORDERS.TEMPLATE_ORDER_ID
		END AS ORIG_ORDER_ID,
		pi_from_gmt(CLINICAL_EVENT.EVENT_END_DT_TM, 'America/Chicago') AS MED_DATETIME,
		CLINICAL_EVENT.EVENT_ID,
		pi_get_cv_display(MED_ADMIN_EVENT.EVENT_TYPE_CD) AS ADMIN_EVENT,
		pi_get_cv_display(ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD) AS NURSE_UNIT,
		pi_get_cv_display(ENCNTR_LOC_HIST.MED_SERVICE_CD) AS MED_SERVICE
	FROM
		-- CE_MED_RESULT,
		CLINICAL_EVENT,
		ENCNTR_LOC_HIST,
		MED_ADMIN_EVENT,
		ORDERS
	WHERE
		CLINICAL_EVENT.EVENT_CD = 37557146 -- heparin
		AND CLINICAL_EVENT.EVENT_END_DT_TM BETWEEN
            pi_to_gmt(
                TO_DATE(
                    @Prompt('Enter begin date', 'D', , mono, free, persistent, {'12/01/2021 00:00:00'}, User:0), 
                    pi_get_dm_info_char_gen('Date Format Mask|FT','PI EXP|Systems Configuration|Date Format Mask')
                ), 
                pi_time_zone(1, 'America/Chicago')
            )
            AND pi_to_gmt(
                TO_DATE(
                    @Prompt('Enter end date', 'D', , mono, free, persistent, {'12/01/2022 00:00:00'}, User:1), 
                    pi_get_dm_info_char_gen('Date Format Mask|FT','PI EXP|Systems Configuration|Date Format Mask')
                ) - 1/86400, 
                pi_time_zone(1, 'America/Chicago')
            )	
		AND CLINICAL_EVENT.VALID_UNTIL_DT_TM > DATE '2099-12-31'
		-- AND CLINICAL_EVENT.EVENT_ID = CE_MED_RESULT.EVENT_ID(+)
		-- AND CE_MED_RESULT.VALID_UNTIL_DT_TM(+) > DATE '2099-12-31'
		AND CLINICAL_EVENT.EVENT_ID = MED_ADMIN_EVENT.EVENT_ID
		AND CLINICAL_EVENT.ORDER_ID = ORDERS.ORDER_ID	
		AND CLINICAL_EVENT.ENCNTR_ID = ENCNTR_LOC_HIST.ENCNTR_ID
		AND ENCNTR_LOC_HIST.BEG_EFFECTIVE_DT_TM <= CLINICAL_EVENT.EVENT_END_DT_TM
		AND ENCNTR_LOC_HIST.TRANSACTION_DT_TM = (
			SELECT MAX(ELH.TRANSACTION_DT_TM)
			FROM ENCNTR_LOC_HIST ELH
			WHERE
				CLINICAL_EVENT.ENCNTR_ID = ELH.ENCNTR_ID
				AND ELH.TRANSACTION_DT_TM <= CLINICAL_EVENT.EVENT_END_DT_TM
		)
		AND ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD IN (
			193270, -- HH STRK
			79976037, -- HH NIMU
			283905037, -- HH 7J
			2041371668, -- HH NVIC
			2203730260, -- HH 5JP
			3547883869 -- HH MED9
		)
		AND ENCNTR_LOC_HIST.END_EFFECTIVE_DT_TM >= CLINICAL_EVENT.EVENT_END_DT_TM
		AND ENCNTR_LOC_HIST.ACTIVE_IND = 1
), ORDER_ROUTE AS (
	SELECT
		DOSES.*,
		ORDER_DETAIL.OE_FIELD_DISPLAY_VALUE AS RXROUTE
	FROM
		DOSES,
		ORDER_DETAIL,
		ORDERS
	WHERE
		DOSES.ORIG_ORDER_ID = ORDERS.ORDER_ID
		AND ORDERS.ORDER_ID = ORDER_DETAIL.ORDER_ID
		AND ORDER_DETAIL.OE_FIELD_MEANING_ID = 2050 -- RXROUTE
		AND ORDER_DETAIL.ACTION_SEQUENCE = 1
)

SELECT
	ORDER_ROUTE.NURSE_UNIT,
	ORDER_ROUTE.ADMIN_EVENT,
	COUNT(DISTINCT ORDER_ROUTE.EVENT_ID) AS NUM_EVENTS
FROM
	ORDER_ROUTE
WHERE
	ORDER_ROUTE.RXROUTE = 'SUB-Q'
GROUP BY
	ORDER_ROUTE.NURSE_UNIT,
	ORDER_ROUTE.ADMIN_EVENT