WITH LABS_PCR AS (
    SELECT DISTINCT
        CLINICAL_EVENT.ENCNTR_ID,
		CLINICAL_EVENT.PERSON_ID,
		CLINICAL_EVENT.EVENT_ID,
		pi_from_gmt(CLINICAL_EVENT.EVENT_END_DT_TM, 'America/Chicago') AS PCR_COLLECTED_DATETIME,
		-- TRUNC(pi_from_gmt(CLINICAL_EVENT.EVENT_END_DT_TM, 'America/Chicago')) AS COLLECTED_DATE
		CLINICAL_EVENT.RESULT_VAL,
		pi_get_cv_display(ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD) AS PCR_NURSE_UNIT
    FROM
        CLINICAL_EVENT,
        ENCNTR_LOC_HIST,
        ENCOUNTER
    WHERE
		CLINICAL_EVENT.EVENT_CD = 221174359 -- MRSA by PCR
        AND CLINICAL_EVENT.EVENT_CLASS_CD = 162 -- TXT
		AND CLINICAL_EVENT.EVENT_END_DT_TM BETWEEN
			pi_to_gmt(
				TO_DATE(
					@Prompt('Enter begin date', 'D', , mono, free, persistent, {'10/01/2020 00:00:00'}, User:0), 
					pi_get_dm_info_char_gen('Date Format Mask|FT','PI EXP|Systems Configuration|Date Format Mask')
				), 
				'America/Chicago'
			)
			AND pi_to_gmt(
				TO_DATE(
					@Prompt('Enter end date', 'D', , mono, free, persistent, {'10/01/2024 00:00:00'}, User:1), 
					pi_get_dm_info_char_gen('Date Format Mask|FT','PI EXP|Systems Configuration|Date Format Mask')
				) - 1/86400, 
				'America/Chicago'
			)
		AND CLINICAL_EVENT.VALID_UNTIL_DT_TM > DATE '2099-12-31'
		AND CLINICAL_EVENT.ENCNTR_ID = ENCNTR_LOC_HIST.ENCNTR_ID
		AND ENCNTR_LOC_HIST.BEG_EFFECTIVE_DT_TM <= CLINICAL_EVENT.EVENT_END_DT_TM
		AND ENCNTR_LOC_HIST.TRANSACTION_DT_TM = (
			SELECT MAX(ELH.TRANSACTION_DT_TM)
			FROM ENCNTR_LOC_HIST ELH
			WHERE
				CLINICAL_EVENT.ENCNTR_ID = ELH.ENCNTR_ID
				AND ELH.TRANSACTION_DT_TM <= CLINICAL_EVENT.EVENT_END_DT_TM
				AND ELH.ACTIVE_IND = 1
		)
		AND ENCNTR_LOC_HIST.END_EFFECTIVE_DT_TM >= CLINICAL_EVENT.EVENT_END_DT_TM
		AND ENCNTR_LOC_HIST.ACTIVE_IND = 1
		AND ENCNTR_LOC_HIST.LOC_FACILITY_CD = 3310 -- HH HERMANN
		AND ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD IN (
			4137, -- HH CCU
			5541, -- HH CVICU
			283905037, -- HH 7J
			1993318732, -- HH HFIC
			2369096643, -- HH TSCU
			2041371668, -- HH NVIC
			3311213379, -- HH TICU
			3224987721, -- HH S STIC
			3224988589, -- HH S SHIC
			3224988925, -- HH S TSIC
			3392290381 -- HH S MICU
		)
        AND CLINICAL_EVENT.ENCNTR_ID = ENCOUNTER.ENCNTR_ID
		AND ENCOUNTER.ENCNTR_TYPE_CLASS_CD IN (
			42631, -- Inpatient
			-- 55851, -- Emergency
			688523 -- Observation
		)
), PATIENTS AS (
	SELECT
		ENCNTR_ID,
		PERSON_ID,
		PCR_NURSE_UNIT,
		RESULT_VAL,
		MIN(PCR_COLLECTED_DATETIME) AS PCR_COLLECTED_DATETIME
		-- COUNT(DISTINCT EVENT_ID) AS NUM_PCR
	FROM
		LABS_PCR
	WHERE
		-- RESULT_VAL IN ('Negative', 'Positive')
		RESULT_VAL = 'Negative'
	GROUP BY
		ENCNTR_ID,
		PERSON_ID,
		PCR_NURSE_UNIT,
		RESULT_VAL
) , CULTURES AS (
	SELECT DISTINCT
		PATIENTS.ENCNTR_ID,
		-- PATIENTS.PERSON_ID,
		-- TO_CHAR(pi_from_gmt(CLINICAL_EVENT.EVENT_END_DT_TM, 'America/Chicago'), 'YYYY-MM-DD"T"HH24:MI:SS') AS COLLECTED_DATETIME,
		-- TO_CHAR(pi_from_gmt(CLINICAL_EVENT.VALID_FROM_DT_TM, 'America/Chicago'), 'YYYY-MM-DD"T"HH24:MI:SS') AS RESULT_DATETIME,
		pi_from_gmt(CLINICAL_EVENT.EVENT_END_DT_TM, 'America/Chicago') AS COLLECTED_DATETIME,
		pi_from_gmt(CLINICAL_EVENT.VALID_FROM_DT_TM, 'America/Chicago') AS RESULT_DATETIME,
		CLINICAL_EVENT.EVENT_ID,
		CLINICAL_EVENT.ACCESSION_NBR,
		pi_get_cv_display(CLINICAL_EVENT.EVENT_CD) AS CULTURE,
		pi_get_cv_display(CE_SPECIMEN_COLL.SOURCE_TYPE_CD) AS SOURCE,
		CLINICAL_EVENT.EVENT_TAG,
		pi_get_cv_display(ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD) AS NURSE_UNIT
	FROM
		CE_SPECIMEN_COLL,
		CLINICAL_EVENT,
		ENCNTR_LOC_HIST,
		PATIENTS
	WHERE
		-- PATIENTS.NUM_PCR > 1
		PATIENTS.ENCNTR_ID = CLINICAL_EVENT.ENCNTR_ID
		AND CLINICAL_EVENT.EVENT_CLASS_CD = 156 -- MBO
		AND PATIENTS.PERSON_ID = CLINICAL_EVENT.PERSON_ID
        AND CLINICAL_EVENT.EVENT_CD IN (
            33212, -- Culture: BAL Quantitative w/Gram Stain
            33260, -- Culture: Respiratory w/Gram Stain
            239955157, -- Culture: Bronch Brush Quant w/Gram Stain
            1159026908, -- Culture: Bronch Wash Quant w/GS
            1844926636 -- Culture: BAL Quant w/GS Transplant
        )
		AND CLINICAL_EVENT.VALID_UNTIL_DT_TM > DATE '2099-12-31'
		AND CLINICAL_EVENT.ENCNTR_ID = ENCNTR_LOC_HIST.ENCNTR_ID
		AND ENCNTR_LOC_HIST.BEG_EFFECTIVE_DT_TM <= CLINICAL_EVENT.EVENT_END_DT_TM
		AND ENCNTR_LOC_HIST.TRANSACTION_DT_TM = (
			SELECT MAX(ELH.TRANSACTION_DT_TM)
			FROM ENCNTR_LOC_HIST ELH
			WHERE
				CLINICAL_EVENT.ENCNTR_ID = ELH.ENCNTR_ID
				AND ELH.TRANSACTION_DT_TM <= CLINICAL_EVENT.EVENT_END_DT_TM
		)
		AND ENCNTR_LOC_HIST.END_EFFECTIVE_DT_TM >= CLINICAL_EVENT.EVENT_END_DT_TM
		AND ENCNTR_LOC_HIST.ACTIVE_IND = 1
		AND CLINICAL_EVENT.EVENT_ID = CE_SPECIMEN_COLL.EVENT_ID(+)
), CULTURE_RES AS (
	SELECT DISTINCT
		CLINICAL_EVENT.ENCNTR_ID,
		CLINICAL_EVENT.PARENT_EVENT_ID,
		CULTURES.COLLECTED_DATETIME,
		CULTURES.NURSE_UNIT,
		CULTURES.CULTURE,
		CE_MICROBIOLOGY.EVENT_ID,
		CE_MICROBIOLOGY.MICRO_SEQ_NBR,
		-- CE_MICROBIOLOGY.VALID_FROM_DT_TM,
		CODE_VALUE.DESCRIPTION AS ORGANISM
	FROM
		CE_MICROBIOLOGY,
		CLINICAL_EVENT,
		CODE_VALUE,
		CULTURES
	WHERE
		CULTURES.EVENT_ID = CLINICAL_EVENT.PARENT_EVENT_ID
		AND CLINICAL_EVENT.EVENT_CD = 31616 -- Final
		AND CLINICAL_EVENT.EVENT_ID = CE_MICROBIOLOGY.EVENT_ID
		AND CE_MICROBIOLOGY.VALID_UNTIL_DT_TM > DATE '2099-12-31'
		AND CE_MICROBIOLOGY.ORGANISM_CD = CODE_VALUE.CODE_VALUE
/* ), CULTURE_SUSCEPT AS (
	SELECT DISTINCT
		CULTURE_RES.ENCNTR_ID,
		CULTURE_RES.PARENT_EVENT_ID,
		CULTURE_RES.COLLECTED_DATETIME,
		CULTURE_RES.NURSE_UNIT,
		CULTURE_RES.CULTURE,
		CULTURE_RES.ORGANISM,
		CE_SUSCEPTIBILITY.MICRO_SEQ_NBR,
		pi_get_cv_display(CE_SUSCEPTIBILITY.DETAIL_SUSCEPTIBILITY_CD) AS DETAIL_SUSCEPT,
		CODE_VALUE.DESCRIPTION AS ANTIBIOTIC,
		pi_get_cv_display(CE_SUSCEPTIBILITY.RESULT_CD) AS SUSCEPTIBILITY
	FROM
		CE_SUSCEPTIBILITY,
		CODE_VALUE,
		CULTURE_RES
	WHERE
		CULTURE_RES.PARENT_EVENT_ID = CE_SUSCEPTIBILITY.EVENT_ID
		AND CULTURE_RES.MICRO_SEQ_NBR = CE_SUSCEPTIBILITY.MICRO_SEQ_NBR
		AND CULTURE_RES.ORGANISM IN ('Staphylococcus aureus', 'Methicillin Resistant Staphylococcus aureus')
		AND CE_SUSCEPTIBILITY.ANTIBIOTIC_CD = CODE_VALUE.CODE_VALUE */
), SUSCEPT_MRSA AS (
	SELECT *
	FROM CULTURE_RES
	WHERE CULTURE_RES.ORGANISM = 'Methicillin Resistant Staphylococcus aureus'
/* 	SELECT * 
	FROM 
		CULTURE_SUSCEPT
	WHERE 
		(CULTURE_SUSCEPT.ANTIBIOTIC IN ('Oxacillin', 'Methicillin')	AND CULTURE_SUSCEPT.SUSCEPTIBILITY = 'R')
		OR CULTURE_SUSCEPT.ORGANISM = 'Methicillin Resistant Staphylococcus aureus' */
)

SELECT DISTINCT
	PATIENTS.*,
    SUSCEPT_MRSA.COLLECTED_DATETIME,
	SUSCEPT_MRSA.CULTURE,
    SUSCEPT_MRSA.ORGANISM,
	-- SUSCEPT_MRSA.ANTIBIOTIC,
	-- SUSCEPT_MRSA.SUSCEPTIBILITY,
	SUSCEPT_MRSA.NURSE_UNIT
    -- CULTURE_RES.MICRO_SEQ_NBR,
FROM
	PATIENTS,
	SUSCEPT_MRSA
WHERE
	PATIENTS.ENCNTR_ID = SUSCEPT_MRSA.ENCNTR_ID(+)
