SELECT DISTINCT
	ENCNTR_ALIAS.ALIAS AS FIN,
	ENCOUNTER.ENCNTR_ID,
	pi_from_gmt(ENCOUNTER.REG_DT_TM, 'America/Chicago') AS ADMIT_DATETIME,
	pi_from_gmt(ENCOUNTER.DISCH_DT_TM, 'America/Chicago') AS DISCH_DATETIME,
	DIAGNOSIS.DIAG_PRIORITY,
    NOMENCLATURE.SOURCE_IDENTIFIER AS ICD_10_CODE,
    NOMENCLATURE.SOURCE_STRING
FROM
	DIAGNOSIS,
	ENCNTR_ALIAS,
	ENCNTR_LOC_HIST,
	ENCOUNTER,
	NOMENCLATURE
WHERE
	ENCOUNTER.ORGANIZATION_ID = 1 -- Memorial Hermann Hospital
	AND ENCOUNTER.REG_DT_TM BETWEEN 
		pi_to_gmt(
			TO_DATE(
				@Prompt('Enter begin date', 'D', , mono, free, persistent, {'01/01/2018 00:00:00'}, User:0), 
				pi_get_dm_info_char_gen('Date Format Mask|FT','PI EXP|Systems Configuration|Date Format Mask')
			), 
			'America/Chicago'
		)
		AND pi_to_gmt(
			TO_DATE(
				@Prompt('Enter end date', 'D', , mono, free, persistent, {'12/01/2022 00:00:00'}, User:1), 
				pi_get_dm_info_char_gen('Date Format Mask|FT','PI EXP|Systems Configuration|Date Format Mask')
			) - 1/86400, 
			'America/Chicago'
		)
	AND ENCOUNTER.DISCH_DT_TM < DATE '2022-12-01'
	AND ENCOUNTER.LOC_FACILITY_CD = 3310 -- HH HERMANN
	-- AND ENCOUNTER.ENCNTR_TYPE_CD IN (
		-- 29532, -- Inpatient
		-- 29540 -- Observation			
	-- )
	-- AND ENCOUNTER.ADMIT_SRC_CD = 9061 -- Emergency Room
	AND ENCOUNTER.ENCNTR_ID = DIAGNOSIS.ENCNTR_ID
	AND DIAGNOSIS.DIAG_TYPE_CD = 26244 -- Final
	-- AND DIAGNOSIS.DIAG_PRIORITY = 1
	AND DIAGNOSIS.NOMENCLATURE_ID = NOMENCLATURE.NOMENCLATURE_ID
	AND REGEXP_INSTR(NOMENCLATURE.SOURCE_IDENTIFIER, '^I26.02|I26.09|I26.92|I26.99') > 0
	AND NOMENCLATURE.SOURCE_VOCABULARY_CD = 641836527 -- ICD-10-CM
	AND NOMENCLATURE.PRINCIPLE_TYPE_CD = 751 -- Disease or Syndrome
	AND ENCOUNTER.ENCNTR_ID = ENCNTR_LOC_HIST.ENCNTR_ID
	AND ENCNTR_LOC_HIST.ACTIVE_IND = 1
	AND ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD IN (
			4501, -- HH 5EJP
			4601, -- HH 5WJP
			193270, -- HH STRK
			79976037, -- HH NIMU
			283905037, -- HH 7J
			2041371668, -- HH NVIC
			3547883869 -- HH MED9	
	)
	AND ENCOUNTER.ENCNTR_ID = ENCNTR_ALIAS.ENCNTR_ID
	AND ENCNTR_ALIAS.ENCNTR_ALIAS_TYPE_CD = 619 -- FIN NBR
	AND ENCNTR_ALIAS.ACTIVE_IND = 1
