WITH PATIENTS AS (
	SELECT DISTINCT
		ENCOUNTER.ENCNTR_ID,
		ENCOUNTER.PERSON_ID
		-- NOMENCLATURE.SOURCE_IDENTIFIER AS ICD_10_CODE,
		-- NOMENCLATURE.SOURCE_STRING	
	FROM
		DIAGNOSIS,
		ENCOUNTER,
		NOMENCLATURE,
		PERSON
	WHERE
		ENCOUNTER.ORGANIZATION_ID = 1 -- Memorial Hermann Hospital
		AND ENCOUNTER.REG_DT_TM BETWEEN 
			pi_to_gmt(
				TO_DATE(
					@Prompt('Enter begin date', 'D', , mono, free, persistent, {'06/01/2018 00:00:00'}, User:0), 
					pi_get_dm_info_char_gen('Date Format Mask|FT','PI EXP|Systems Configuration|Date Format Mask')
				), 
				'America/Chicago'
			)
			AND pi_to_gmt(
				TO_DATE(
					@Prompt('Enter end date', 'D', , mono, free, persistent, {'06/01/2023 00:00:00'}, User:1), 
					pi_get_dm_info_char_gen('Date Format Mask|FT','PI EXP|Systems Configuration|Date Format Mask')
				) - 1/86400, 
				'America/Chicago'
			)
		AND ENCOUNTER.LOC_FACILITY_CD = 3310 -- HH HERMANN
		-- AND ENCOUNTER.ADMIT_SRC_CD = 9061 -- Emergency Room
		AND ENCOUNTER.ENCNTR_ID = DIAGNOSIS.ENCNTR_ID
		AND DIAGNOSIS.DIAG_TYPE_CD = 26244 -- Final
		-- AND DIAGNOSIS.DIAG_PRIORITY = 1
		AND DIAGNOSIS.NOMENCLATURE_ID = NOMENCLATURE.NOMENCLATURE_ID
		AND REGEXP_INSTR(NOMENCLATURE.SOURCE_IDENTIFIER, '^S0[1-9]') > 0
		AND NOMENCLATURE.SOURCE_VOCABULARY_CD = 641836527 -- ICD-10-CM
		AND NOMENCLATURE.PRINCIPLE_TYPE_CD = 751 -- Disease or Syndrome
		AND ENCOUNTER.PERSON_ID = PERSON.PERSON_ID
		AND TRUNC((TRUNC(pi_from_gmt(ENCOUNTER.REG_DT_TM, 'America/Chicago')) - TRUNC(pi_from_gmt(PERSON.BIRTH_DT_TM, 'America/Chicago'))) / 365.25, 0) >= 18
), EXCL_PTS AS (
	SELECT DISTINCT
		PATIENTS.ENCNTR_ID
	FROM
		DIAGNOSIS,
		NOMENCLATURE,
		PATIENTS
	WHERE
		PATIENTS.ENCNTR_ID = DIAGNOSIS.ENCNTR_ID
		AND DIAGNOSIS.DIAG_TYPE_CD = 26244 -- Final
		AND DIAGNOSIS.NOMENCLATURE_ID = NOMENCLATURE.NOMENCLATURE_ID
		AND REGEXP_INSTR(NOMENCLATURE.SOURCE_IDENTIFIER, '^G40.901|^G40.909') > 0
		AND NOMENCLATURE.SOURCE_VOCABULARY_CD = 641836527 -- ICD-10-CM
		AND NOMENCLATURE.PRINCIPLE_TYPE_CD = 751 -- Disease or Syndrome
), DOSES AS (
	SELECT DISTINCT
		PATIENTS.ENCNTR_ID,
		pi_get_cv_display(CLINICAL_EVENT.EVENT_CD) AS MEDICATION,
		MIN(pi_from_gmt(CLINICAL_EVENT.EVENT_END_DT_TM, 'America/Chicago')) AS FIRST_DOSE_DATETIME
	FROM
		CE_MED_RESULT,
		CLINICAL_EVENT,
		PATIENTS
	WHERE
		PATIENTS.ENCNTR_ID = CLINICAL_EVENT.ENCNTR_ID
		AND CLINICAL_EVENT.EVENT_CLASS_CD = 158 -- MED
		AND PATIENTS.PERSON_ID = CLINICAL_EVENT.PERSON_ID
		AND CLINICAL_EVENT.EVENT_CD IN (
			37557411, -- levetiracetam
			37556785, -- divalproex sodium
			37558313 -- valproic acid
		)
		AND CLINICAL_EVENT.VALID_UNTIL_DT_TM > DATE '2099-12-31'
		AND CLINICAL_EVENT.EVENT_ID = CE_MED_RESULT.EVENT_ID
		AND CE_MED_RESULT.VALID_UNTIL_DT_TM > DATE '2099-12-31'
	GROUP BY
		PATIENTS.ENCNTR_ID,
		pi_get_cv_display(CLINICAL_EVENT.EVENT_CD)		
), DOSES_PIVOT AS (
	SELECT * FROM DOSES
	PIVOT(
		MIN(FIRST_DOSE_DATETIME) FOR MEDICATION IN (
			'levetiracetam' AS LEVETIRACETAM,
			'divalproex sodium' AS DIVALPROEX_SODIUM,
			'valproic acid' AS VALPROIC_ACID
		)
	)
), HOME_MEDS AS (
	SELECT DISTINCT
		PATIENTS.ENCNTR_ID,
		pi_get_cv_display(ORDERS.CATALOG_CD) AS HOME_MED,
		'TRUE' AS MED
	FROM
		ORDERS,
		PATIENTS
	WHERE
		PATIENTS.ENCNTR_ID = ORDERS.ENCNTR_ID
		AND ORDERS.CATALOG_CD IN (
			9903056, -- valproic acid
			9911484, -- divalproex sodium
			9913491 -- levETIRAcetam
		)
		AND ORDERS.ORIG_ORD_AS_FLAG = 2 -- Recorded/Home Meds
), HOME_MEDS_PIVOT AS (
	SELECT * FROM HOME_MEDS
	PIVOT(
		MIN(MED) FOR HOME_MED IN (
			'levETIRAcetam' AS HOME_LEVETIRACETAM,
			'divalproex sodium' AS HOME_DIVALPROEX_SODIUM,
			'valproic acid' AS HOME_VALPROIC_ACID
		)
	)
), BEHAVIORS AS (
	SELECT DISTINCT
		PATIENTS.ENCNTR_ID,
		pi_from_gmt(CLINICAL_EVENT.EVENT_END_DT_TM, 'America/Chicago') AS EVENT_DATETIME,
		CLINICAL_EVENT.EVENT_ID,
		pi_get_cv_display(CLINICAL_EVENT.EVENT_CD) AS EVENT,
		CLINICAL_EVENT.RESULT_VAL
	FROM
		CLINICAL_EVENT,
		PATIENTS
	WHERE
		PATIENTS.ENCNTR_ID NOT IN (SELECT ENCNTR_ID FROM EXCL_PTS)
		AND PATIENTS.ENCNTR_ID = CLINICAL_EVENT.ENCNTR_ID
		-- AND CLINICAL_EVENT.EVENT_CLASS_CD = 158 -- MED
		AND PATIENTS.PERSON_ID = CLINICAL_EVENT.PERSON_ID
		AND CLINICAL_EVENT.EVENT_CD IN (
			917007440, -- JH Cognition
			-- 134394075, -- Level of Consciousness
			-- 898374263, -- Consciousness Level
			173564915, -- (CAM-ICU) Interpretation
			-- 3302503975, -- Complete Suicide Risk Assessment
			3859920837, -- Complete Suicide Risk (PSS-3)
			3860481871 -- Behavioral Risk Assessment History
		)
		AND CLINICAL_EVENT.VALID_UNTIL_DT_TM > DATE '2099-12-31'
), AGITATION AS (
	SELECT 
		BEHAVIORS.ENCNTR_ID,
		BEHAVIORS.EVENT,
		BEHAVIORS.RESULT_VAL
	FROM
		BEHAVIORS
	WHERE
		(BEHAVIORS.EVENT = 'JH Cognition' AND REGEXP_INSTR(BEHAVIORS.RESULT_VAL, 'Impulsive') > 0)
		OR (BEHAVIORS.EVENT = '(CAM-ICU) Interpretation' AND BEHAVIORS.RESULT_VAL = 'Positive')
		OR (BEHAVIORS.EVENT = 'Behavioral Risk Assessment History' AND REGEXP_INSTR(BEHAVIORS.RESULT_VAL, 'Brain injury') > 0 AND REGEXP_INSTR(BEHAVIORS.RESULT_VAL, 'Dementia/Delirium') > 0)
		OR (BEHAVIORS.EVENT = 'Complete Suicide Risk (PSS-3)' AND BEHAVIORS.RESULT_VAL = 'Yes')
), AGITATION_PIVOT AS (
	SELECT * FROM AGITATION
	PIVOT(
		MIN(RESULT_VAL) FOR EVENT IN (
			'JH Cognition' AS JH_COGNITION,
			'(CAM-ICU) Interpretation' AS CAM_ICU,
			'Behavioral Risk Assessment History' AS BEHAVIOR_RISK,
			'Complete Suicide Risk (PSS-3)' AS SUICIDE_RISK
		)
	)
)

SELECT
	ENCNTR_ALIAS.ALIAS AS FIN,
	PATIENTS.*,
	DOSES_PIVOT.LEVETIRACETAM,
	DOSES_PIVOT.DIVALPROEX_SODIUM,
	DOSES_PIVOT.VALPROIC_ACID,
	HOME_MEDS_PIVOT.HOME_LEVETIRACETAM,
	HOME_MEDS_PIVOT.HOME_DIVALPROEX_SODIUM,
	HOME_MEDS_PIVOT.HOME_VALPROIC_ACID,
	AGITATION_PIVOT.JH_COGNITION,
	AGITATION_PIVOT.CAM_ICU,
	AGITATION_PIVOT.BEHAVIOR_RISK,
	AGITATION_PIVOT.SUICIDE_RISK
FROM
	AGITATION_PIVOT,
	DOSES_PIVOT,
	ENCNTR_ALIAS,
	HOME_MEDS_PIVOT,
	PATIENTS
WHERE
	PATIENTS.ENCNTR_ID NOT IN (SELECT ENCNTR_ID FROM EXCL_PTS)
	AND PATIENTS.ENCNTR_ID = DOSES_PIVOT.ENCNTR_ID
	AND PATIENTS.ENCNTR_ID = HOME_MEDS_PIVOT.ENCNTR_ID(+)
	AND PATIENTS.ENCNTR_ID = AGITATION_PIVOT.ENCNTR_ID(+)
	AND PATIENTS.ENCNTR_ID = ENCNTR_ALIAS.ENCNTR_ID
	AND ENCNTR_ALIAS.ENCNTR_ALIAS_TYPE_CD = 619 -- FIN NBR
	AND ENCNTR_ALIAS.ACTIVE_IND = 1
