WITH PATIENTS AS (
	SELECT DISTINCT
		ENCOUNTER.ENCNTR_ID,
		ENCOUNTER.PERSON_ID
	FROM
		ENCOUNTER
	WHERE
	    ENCOUNTER.ENCNTR_ID IN @prompt('Enter value(s) for Encounter ID','A',,Multi,Free,Persistent,,User:0)
)

SELECT DISTINCT
    PATIENTS.ENCNTR_ID,
	DIAGNOSIS.DIAG_PRIORITY,
    NOMENCLATURE.SOURCE_IDENTIFIER AS ICD_10_CODE,
    NOMENCLATURE.SOURCE_STRING AS ICD_10_DESCRIPTION
FROM
    DIAGNOSIS,
    NOMENCLATURE,
    PATIENTS
WHERE
    PATIENTS.ENCNTR_ID = DIAGNOSIS.ENCNTR_ID
    AND DIAGNOSIS.DIAG_TYPE_CD = 26244 -- Final
    AND DIAGNOSIS.NOMENCLATURE_ID = NOMENCLATURE.NOMENCLATURE_ID
    -- AND REGEXP_INSTR(NOMENCLATURE.SOURCE_IDENTIFIER, '^E08|^E10|^E78|^I63|^I68|^F17.2|^I48|^I61.5|^I46') > 0 
    AND NOMENCLATURE.SOURCE_VOCABULARY_CD = 641836527 -- ICD-10-CM
    AND NOMENCLATURE.PRINCIPLE_TYPE_CD = 751 -- Disease or Syndrome