WITH PATIENTS AS (
	SELECT DISTINCT
		ENCOUNTER.ENCNTR_ID,
		ENCOUNTER.PERSON_ID,
		ENCNTR_ALIAS.ALIAS AS FIN
	FROM
		ENCNTR_ALIAS,
		ENCOUNTER
	WHERE
	    ENCNTR_ALIAS.ALIAS IN @prompt('Enter value(s) for Alias','A',,Multi,Free,Persistent,,User:0)
		AND ENCNTR_ALIAS.ENCNTR_ALIAS_TYPE_CD = 619 -- FIN NBR
		AND ENCNTR_ALIAS.ACTIVE_IND = 1
		AND ENCNTR_ALIAS.ENCNTR_ID = ENCOUNTER.ENCNTR_ID
), INS_OUTS AS (
	SELECT DISTINCT
		PATIENTS.ENCNTR_ID,
		PATIENTS.FIN,
		-- TO_CHAR(pi_from_gmt(CLINICAL_EVENT.EVENT_END_DT_TM, 'America/Chicago'), 'YYYY-MM-DD"T"HH24:MI:SS') AS EVENT_DATETIME,
		pi_from_gmt(CLINICAL_EVENT.EVENT_END_DT_TM, 'America/Chicago') AS EVENT_DATETIME,
		CLINICAL_EVENT.EVENT_ID,
		pi_get_cv_display(CLINICAL_EVENT.EVENT_CD) AS EVENT,
		CASE CE_INTAKE_OUTPUT_RESULT.IO_TYPE_FLAG
			WHEN 1 THEN 'IN'
			ELSE 'OUT'
		END AS IO_TYPE,
		CE_INTAKE_OUTPUT_RESULT.IO_VOLUME,
		pi_get_cv_display(ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD) AS NURSE_UNIT
	FROM
		CE_INTAKE_OUTPUT_RESULT,
		CLINICAL_EVENT,
		ENCNTR_LOC_HIST,
		PATIENTS
	WHERE
		PATIENTS.ENCNTR_ID = CLINICAL_EVENT.ENCNTR_ID
		AND CLINICAL_EVENT.EVENT_CD IN (
			699895551, -- PRBC Volume
			699895629, -- FFP Volume
			699895580, -- Platelets Volume
			699895605 -- Cryo Volume
		)
		AND CLINICAL_EVENT.VALID_UNTIL_DT_TM > DATE '2099-12-31'
		AND CLINICAL_EVENT.AUTHENTIC_FLAG = 1
		AND CLINICAL_EVENT.EVENT_ID = CE_INTAKE_OUTPUT_RESULT.EVENT_ID
		AND CE_INTAKE_OUTPUT_RESULT.IO_TYPE_FLAG = 1
		AND CE_INTAKE_OUTPUT_RESULT.VALID_UNTIL_DT_TM > DATE '2099-12-31'
		AND CLINICAL_EVENT.ENCNTR_ID = ENCNTR_LOC_HIST.ENCNTR_ID
		AND ENCNTR_LOC_HIST.BEG_EFFECTIVE_DT_TM <= CLINICAL_EVENT.EVENT_END_DT_TM
		AND ENCNTR_LOC_HIST.TRANSACTION_DT_TM = (
			SELECT MAX(ELH.TRANSACTION_DT_TM)
			FROM ENCNTR_LOC_HIST ELH
			WHERE
				CLINICAL_EVENT.ENCNTR_ID = ELH.ENCNTR_ID
				AND ELH.TRANSACTION_DT_TM <= CLINICAL_EVENT.EVENT_END_DT_TM
				AND ELH.ACTIVE_IND = 1
		)
		AND ENCNTR_LOC_HIST.END_EFFECTIVE_DT_TM >= CLINICAL_EVENT.EVENT_END_DT_TM
		AND ENCNTR_LOC_HIST.ACTIVE_IND = 1
), IO_CHILD AS (
	SELECT DISTINCT
		INS_OUTS.EVENT_ID,
		CLINICAL_EVENT.EVENT_ID AS CHILD_EVENT_ID,
		pi_get_cv_display(CLINICAL_EVENT.EVENT_CD) AS CHILD_EVENT,
		LISTAGG(pi_get_cv_display(CLINICAL_EVENT.EVENT_CD), ', ') WITHIN GROUP (ORDER BY CLINICAL_EVENT.EVENT_ID) AS EVENT_DETAILS		
	FROM
		CLINICAL_EVENT,
		INS_OUTS
	WHERE
		INS_OUTS.EVENT_ID = CLINICAL_EVENT.PARENT_EVENT_ID
		AND CLINICAL_EVENT.EVENT_RELTN_CD = 78 -- CHILD
		AND CLINICAL_EVENT.VALID_UNTIL_DT_TM > DATE '2099-12-31'
	GROUP BY 
		INS_OUTS.EVENT_ID,
		CLINICAL_EVENT.EVENT_ID,
		CLINICAL_EVENT.EVENT_CD
)

SELECT 
	INS_OUTS.*, 
	IO_CHILD.EVENT_DETAILS,
	IO_CHILD.CHILD_EVENT_ID,
	IO_CHILD.CHILD_EVENT
FROM 
	INS_OUTS,
	IO_CHILD
WHERE
	INS_OUTS.EVENT_ID = IO_CHILD.EVENT_ID(+)
