WITH PATIENTS AS (
	SELECT DISTINCT
		ENCOUNTER.ENCNTR_ID,
		ENCOUNTER.PERSON_ID
	FROM
		ENCOUNTER
	WHERE
	    ENCOUNTER.ENCNTR_ID IN @prompt('Enter value(s) for Encntr Id','A',,Multi,Free,Persistent,,User:0)
)

SELECT DISTINCT
	PATIENTS.ENCNTR_ID,
	ORDERS.ORDER_ID,
	pi_get_cv_display(ORDERS.CATALOG_CD) AS MEDICATION,
	ORDERS.ORDERED_AS_MNEMONIC,
	PI_THERA_CLASS_VIEW.DRUG_CAT
FROM
	ORDERS,
	PATIENTS,
	PI_THERA_CLASS_VIEW
WHERE
	PATIENTS.ENCNTR_ID = ORDERS.ENCNTR_ID
	AND ORDERS.ORIG_ORD_AS_FLAG = 2 -- Recorded/Home Medication
	AND ORDERS.CATALOG_CD = PI_THERA_CLASS_VIEW.DRUG_CAT_CD(+)
