WITH PATIENTS AS (
	SELECT DISTINCT
		ENCOUNTER.ENCNTR_ID,
		ENCOUNTER.PERSON_ID,
		ENCNTR_ALIAS.ALIAS AS FIN,
		-- ENCOUNTER.REG_DT_TM,
		pi_from_gmt(ENCOUNTER.REG_DT_TM, 'America/Chicago') AS ADMIT_DATETIME,
		pi_get_cv_display(ENCOUNTER.LOC_FACILITY_CD) AS FACILITY
	FROM
		ENCNTR_ALIAS,
		ENCOUNTER
	WHERE
	    ENCNTR_ALIAS.ALIAS IN @prompt('Enter value(s) for Alias','A',,Multi,Free,Persistent,,User:0)
		AND ENCNTR_ALIAS.ENCNTR_ALIAS_TYPE_CD = 619 -- FIN NBR
		AND ENCNTR_ALIAS.ACTIVE_IND = 1
		AND ENCNTR_ALIAS.ENCNTR_ID = ENCOUNTER.ENCNTR_ID
), ANTICOAG AS (
	SELECT DISTINCT
		PATIENTS.ENCNTR_ID,
		CASE
			WHEN CLINICAL_EVENT.EVENT_CD IN (37556169, 37556170) THEN 'argatroban'
			ELSE pi_get_cv_display(CLINICAL_EVENT.EVENT_CD) 
		END AS MEDICATION,
		'TRUE' AS MED
	FROM
		CE_MED_RESULT,
		CLINICAL_EVENT,
		PATIENTS
	WHERE
		PATIENTS.ENCNTR_ID = CLINICAL_EVENT.ENCNTR_ID
		AND CLINICAL_EVENT.EVENT_CLASS_CD = 158 -- MED
		AND PATIENTS.PERSON_ID = CLINICAL_EVENT.PERSON_ID
		AND CLINICAL_EVENT.EVENT_CD IN (
			37557146, -- heparin
			37556844, -- enoxaparin		
			37556313, -- bivalirudin
			37556169, -- argatroban
			37556170, -- argatroban 100mg/ml INJ 2.5ml
			37557027, -- fondaparinux
			37558355, -- warfarin
			535736194, -- dabigatran
			642177890, -- rivaroxaban
			894197564 -- apixaban
		)
		AND CLINICAL_EVENT.VALID_UNTIL_DT_TM > DATE '2099-12-31'
		AND CLINICAL_EVENT.EVENT_ID = CE_MED_RESULT.EVENT_ID
		AND CE_MED_RESULT.VALID_UNTIL_DT_TM > DATE '2099-12-31'
		AND (
			(CLINICAL_EVENT.EVENT_CD IN (37557146, 37556313, 37556169, 37556170) AND CE_MED_RESULT.IV_EVENT_CD > 0)
			OR (CLINICAL_EVENT.EVENT_CD = 37556844 AND CE_MED_RESULT.ADMIN_DOSAGE > 40)
			OR (CLINICAL_EVENT.EVENT_CD IN (37557027, 37558355, 535736194, 642177890, 894197564, 1466817862))
		)
), ANTICOAG_PIVOT AS (
	SELECT * FROM ANTICOAG
	PIVOT(
		MIN(MED) FOR MEDICATION IN (
			'heparin' AS HEPARIN,
			'enoxaparin' AS ENOXAPARIN,
			'bivalirudin' AS BIVALIRUDIN,
			'argatroban' AS ARGATROBAN,
			'fondaparinux' AS FONDAPARINUX,
			'warfarin' AS WARFARIN,
			'dabigatran' AS DABIGATRAN,
			'rivaroxaban' AS RIVAROXABAN,
			'apixaban' AS APIXABAN
		)
	)
)

SELECT DISTINCT
	PATIENTS.ENCNTR_ID,
	PATIENTS.FIN,
	PATIENTS.ADMIT_DATETIME,
	PATIENTS.FACILITY,
	ANTICOAG_PIVOT.HEPARIN,
	ANTICOAG_PIVOT.ENOXAPARIN,
	ANTICOAG_PIVOT.BIVALIRUDIN,
	ANTICOAG_PIVOT.ARGATROBAN,
	ANTICOAG_PIVOT.FONDAPARINUX,
	ANTICOAG_PIVOT.WARFARIN,
	ANTICOAG_PIVOT.DABIGATRAN,
	ANTICOAG_PIVOT.RIVAROXABAN,
	ANTICOAG_PIVOT.APIXABAN	
FROM
	ANTICOAG_PIVOT,
	PATIENTS
WHERE
	PATIENTS.ENCNTR_ID = ANTICOAG_PIVOT.ENCNTR_ID(+)