WITH PATIENTS AS (
	SELECT DISTINCT
		ENCOUNTER.ENCNTR_ID,
		ENCOUNTER.PERSON_ID,
		ENCOUNTER.REG_DT_TM
	FROM
		DIAGNOSIS,
		ENCOUNTER,
		NOMENCLATURE,
		PERSON
	WHERE
		ENCOUNTER.ORGANIZATION_ID = 1 -- Memorial Hermann Hospital
		AND ENCOUNTER.REG_DT_TM BETWEEN 
			pi_to_gmt(
				TO_DATE(
					@Prompt('Enter begin date', 'D', , mono, free, persistent, {'07/01/2017 00:00:00'}, User:0), 
					pi_get_dm_info_char_gen('Date Format Mask|FT','PI EXP|Systems Configuration|Date Format Mask')
				), 
				pi_time_zone(1, @Variable('BOUSER'))
			)
			AND pi_to_gmt(
				TO_DATE(
					@Prompt('Enter end date', 'D', , mono, free, persistent, {'07/01/2020 00:00:00'}, User:1), 
					pi_get_dm_info_char_gen('Date Format Mask|FT','PI EXP|Systems Configuration|Date Format Mask')
				) - 1/86400, 
				pi_time_zone(1, @Variable('BOUSER'))
			)
		AND ENCOUNTER.LOC_FACILITY_CD = 3310 -- HH HERMANN
		-- AND ENCOUNTER.ADMIT_SRC_CD = 9061 -- Emergency Room
		AND ENCOUNTER.ENCNTR_ID = DIAGNOSIS.ENCNTR_ID
		AND DIAGNOSIS.DIAG_TYPE_CD = 26244 -- Final
		AND DIAGNOSIS.DIAG_PRIORITY = 1
		AND DIAGNOSIS.NOMENCLATURE_ID = NOMENCLATURE.NOMENCLATURE_ID
		AND REGEXP_INSTR(NOMENCLATURE.SOURCE_IDENTIFIER, '^I61|^I62') > 0
		AND NOMENCLATURE.SOURCE_VOCABULARY_CD = 641836527 -- ICD-10-CM
		AND NOMENCLATURE.PRINCIPLE_TYPE_CD = 751 -- Disease or Syndrome
		AND ENCOUNTER.PERSON_ID = PERSON.PERSON_ID
		AND TRUNC(((pi_from_gmt(ENCOUNTER.REG_DT_TM, 'America/Chicago')) - PERSON.BIRTH_DT_TM) / 365.25, 0) >= 18
), TFR_LOS AS (
	SELECT DISTINCT
		PATIENTS.ENCNTR_ID,
		ENCOUNTER.ENCNTR_ID AS TFR_ENCNTR_ID,
		ENCOUNTER.DISCH_DT_TM - ENCOUNTER.REG_DT_TM AS TFR_LOS,
		pi_get_cv_display(ENCOUNTER.LOC_FACILITY_CD) AS TFR_FACILITY,
		pi_get_cv_display(ENCOUNTER.ENCNTR_TYPE_CLASS_CD) AS TFR_ENCNTR_TYPE
	FROM
		ENCOUNTER,
		PATIENTS
	WHERE
		PATIENTS.PERSON_ID = ENCOUNTER.PERSON_ID
		AND ENCOUNTER.DISCH_DT_TM BETWEEN PATIENTS.REG_DT_TM - 1 AND PATIENTS.REG_DT_TM
		AND ENCOUNTER.ENCNTR_TYPE_CLASS_CD IN (
			42631, -- Inpatient
			55851, -- Emergency
			688523 -- Observation
		)
), TFR_COUNT AS (
	SELECT
		ENCNTR_ID,
		COUNT(DISTINCT TFR_ENCNTR_ID) AS NUM_PREV_ENCNTR
	FROM TFR_LOS
	GROUP BY ENCNTR_ID
), INCLUDE_PTS AS (
	SELECT *
	FROM PATIENTS
	WHERE PATIENTS.ENCNTR_ID NOT IN (SELECT ENCNTR_ID FROM TFR_COUNT WHERE NUM_PREV_ENCNTR > 1)
), FLUID_DATA AS (
	SELECT DISTINCT
		INCLUDE_PTS.ENCNTR_ID,
		ENCNTR_ALIAS.ALIAS AS FIN,
		CE_INTAKE_OUTPUT_RESULT.IO_END_DT_TM,
		pi_from_gmt(CE_INTAKE_OUTPUT_RESULT.IO_END_DT_TM, 'America/Chicago') AS EVENT_DATETIME,
		CE_INTAKE_OUTPUT_RESULT.EVENT_ID,
		pi_get_cv_display(CE_INTAKE_OUTPUT_RESULT.REFERENCE_EVENT_CD) AS REFERENCE_EVENT,
		-- CLINICAL_EVENT.EVENT_ID AS CHILD_EVENT_ID,
		-- pi_get_cv_display(CLINICAL_EVENT.EVENT_CD) AS EVENT,
		-- CE_INTAKE_OUTPUT_RESULT.IO_TYPE_FLAG,
		CE_INTAKE_OUTPUT_RESULT.IO_VOLUME,
		CASE
			WHEN ORDERS.TEMPLATE_ORDER_ID = 0 THEN ORDERS.ORDER_ID
			ELSE ORDERS.TEMPLATE_ORDER_ID
		END AS ORIG_ORDER_ID
	FROM
		CE_INTAKE_OUTPUT_RESULT,
		CLINICAL_EVENT,
		ENCNTR_ALIAS,
		INCLUDE_PTS,
		ORDERS
	WHERE
		INCLUDE_PTS.ENCNTR_ID = CE_INTAKE_OUTPUT_RESULT.ENCNTR_ID
		AND CE_INTAKE_OUTPUT_RESULT.REFERENCE_EVENT_CD = 34239833 -- Administration Information
		AND CE_INTAKE_OUTPUT_RESULT.IO_TYPE_FLAG = 1
		AND CE_INTAKE_OUTPUT_RESULT.VALID_UNTIL_DT_TM > DATE '2099-12-31'
		AND CE_INTAKE_OUTPUT_RESULT.EVENT_ID = CLINICAL_EVENT.PARENT_EVENT_ID
		AND CLINICAL_EVENT.EVENT_CD <> 34239833 -- Administration Information
		AND CLINICAL_EVENT.VALID_UNTIL_DT_TM > DATE '2099-12-31'
		AND CLINICAL_EVENT.ORDER_ID = ORDERS.ORDER_ID
		AND INCLUDE_PTS.ENCNTR_ID = ENCNTR_ALIAS.ENCNTR_ID
		AND ENCNTR_ALIAS.ENCNTR_ALIAS_TYPE_CD = 619 -- FIN NBR
		AND ENCNTR_ALIAS.ACTIVE_IND = 1
)

SELECT DISTINCT
	FLUID_DATA.*,
	MED_IDENTIFIER.ITEM_ID,
	MED_IDENTIFIER.VALUE AS MED_PRODUCT	
FROM
	FLUID_DATA,
	MED_IDENTIFIER,
	ORDER_PRODUCT
WHERE
	FLUID_DATA.ORIG_ORDER_ID = ORDER_PRODUCT.ORDER_ID
	AND ORDER_PRODUCT.ACTION_SEQUENCE IN (1, 2)
	AND ORDER_PRODUCT.INGRED_SEQUENCE = 1
	AND ORDER_PRODUCT.ITEM_ID = MED_IDENTIFIER.ITEM_ID
	AND MED_IDENTIFIER.MED_IDENTIFIER_TYPE_CD = 1564 -- Description
	AND MED_IDENTIFIER.MED_PRODUCT_ID = 0
	