WITH PATIENTS AS (
	SELECT DISTINCT
		ENCOUNTER.ENCNTR_ID,
		ENCOUNTER.PERSON_ID,
		ENCNTR_ALIAS.ALIAS AS FIN,
		ENCOUNTER.REG_DT_TM,
		ENCOUNTER.DISCH_DT_TM
	FROM
		ENCNTR_ALIAS,
		ENCOUNTER
	WHERE
	    ENCNTR_ALIAS.ALIAS IN @prompt('Enter value(s) for Alias','A',,Multi,Free,Persistent,,User:0)
		AND ENCNTR_ALIAS.ENCNTR_ALIAS_TYPE_CD = 619 -- FIN NBR
		AND ENCNTR_ALIAS.ACTIVE_IND = 1
		AND ENCNTR_ALIAS.ENCNTR_ID = ENCOUNTER.ENCNTR_ID
), ACEI_ALLERGY AS (
	SELECT DISTINCT
		-- PATIENTS.PERSON_ID,
		PATIENTS.ENCNTR_ID,
		ALLERGY.ALLERGY_ID,
		NOMENCLATURE.SOURCE_STRING AS ALLERGY
	FROM
		ALLERGY,
		NOMENCLATURE,
		PATIENTS
	WHERE
		PATIENTS.PERSON_ID = ALLERGY.PERSON_ID
		AND ALLERGY.CREATED_DT_TM < PATIENTS.DISCH_DT_TM
		AND ALLERGY.END_EFFECTIVE_DT_TM >= PATIENTS.REG_DT_TM
		AND ALLERGY.SUBSTANCE_NOM_ID = NOMENCLATURE.NOMENCLATURE_ID
		-- AND REGEXP_INSTR(LOWER(NOMENCLATURE.SOURCE_STRING), 'benazepril|captopril|enalapril|fosinopril|lisinopril|moexipril|perindopril|quinapril|ramipril|trandolapril|ace inhibitor|angiotensin converting enzyme') > 0
)

SELECT DISTINCT
	PATIENTS.ENCNTR_ID,
	PATIENTS.FIN,
	ACEI_ALLERGY.ALLERGY
FROM
	ACEI_ALLERGY,
	PATIENTS
WHERE
	PATIENTS.ENCNTR_ID = ACEI_ALLERGY.ENCNTR_ID
