WITH PATIENTS AS (
	SELECT DISTINCT
		ENCOUNTER.ENCNTR_ID,
		ENCOUNTER.PERSON_ID
	FROM
		ENCOUNTER
	WHERE
	    ENCOUNTER.ENCNTR_ID IN @prompt('Enter value(s) for Encntr Id','A',,Multi,Free,Persistent,,User:0)
), DYE_ORDERS AS (
	SELECT DISTINCT
		PATIENTS.ENCNTR_ID,
		pi_from_gmt(ORDERS.ORIG_ORDER_DT_TM, 'America/Chicago') AS ORDER_DATETIME,
		ORDERS.ORDER_ID,
		pi_get_cv_display(ORDERS.CATALOG_CD) AS MEDICATION,
		pi_get_cv_display(ORDERS.CONTRIBUTOR_SYSTEM_CD) AS CONTRIB_SYS
	FROM
		ORDERS,
		PATIENTS
	WHERE
		PATIENTS.ENCNTR_ID = ORDERS.ENCNTR_ID
		AND ORDERS.CATALOG_CD IN (
			9907439, -- iohexol
			9912006 -- iodixanol
		) 
)

SELECT DISTINCT
	DYE_ORDERS.*,
	ORDER_PRODUCT.ITEM_ID,
	ORDER_PRODUCT.DOSE_QUANTITY,
	pi_get_cv_display(ORDER_PRODUCT.DOSE_QUANTITY_UNIT_CD) AS DOSE_QUANTITY_UNIT,
	MED_IDENTIFIER.VALUE AS PRODUCT
	-- CHARGE.CHARGE_TYPE_CD,
	-- pi_get_cv_display(CHARGE.CHARGE_TYPE_CD) AS CHARGE_TYPE,
	-- CHARGE.ITEM_QUANTITY
FROM
	-- CHARGE,
	DYE_ORDERS,
	MED_IDENTIFIER,
	ORDER_PRODUCT
WHERE
	DYE_ORDERS.ORDER_ID = ORDER_PRODUCT.ORDER_ID
	AND ORDER_PRODUCT.ACTION_SEQUENCE = 1
	AND ORDER_PRODUCT.INGRED_SEQUENCE = 1
	AND ORDER_PRODUCT.ITEM_ID = MED_IDENTIFIER.ITEM_ID
	AND MED_IDENTIFIER.MED_IDENTIFIER_TYPE_CD = 1564 -- Generic Name
	AND MED_IDENTIFIER.MED_PRODUCT_ID = 0
	-- AND DYE_ORDERS.ORDER_ID = CHARGE.ORDER_ID
	-- AND CHARGE.CHARGE_TYPE_CD IN (
		-- 1871, -- CREDIT
		-- 1872 -- DEBIT
	-- )