WITH PATIENTS AS (
	SELECT DISTINCT
		ENCOUNTER.ENCNTR_ID,
		ENCOUNTER.PERSON_ID
	FROM
		ENCOUNTER
	WHERE
	    ENCOUNTER.ENCNTR_ID IN @prompt('Enter value(s) for Encntr Id','A',,Multi,Free,Persistent,,User:0)
)

SELECT DISTINCT
	PATIENTS.ENCNTR_ID,
	pi_from_gmt(CLINICAL_EVENT.EVENT_END_DT_TM, 'America/Chicago') AS EVENT_DATETIME,
	CLINICAL_EVENT.EVENT_ID,
	pi_get_cv_display(CLINICAL_EVENT.EVENT_CD) AS EVENT
FROM
	CLINICAL_EVENT,
	PATIENTS
WHERE
	PATIENTS.ENCNTR_ID = CLINICAL_EVENT.ENCNTR_ID
	--AND CLINICAL_EVENT.EVENT_CLASS_CD = 159 -- NUM
	AND CLINICAL_EVENT.EVENT_CD IN (
		333892069, -- Hemodialysis Output Vol
		333892090, -- Peritoneal Dialysis Output Vol
		333892112, -- CRRT Output Vol
		699896173, -- Hemodialysis Output Volume
		699896249, -- Peritoneal Dialysis Output Volume
		173565025 -- CRRT Actual Pt Fluid Removed Vol
	)
	-- AND CLINICAL_EVENT.EVENT_END_DT_TM >= pi_to_gmt(SYSDATE - 3, 'America/Chicago')
	AND CLINICAL_EVENT.VALID_UNTIL_DT_TM > DATE '2099-12-31'	
