WITH DISCHARGES AS (
	SELECT DISTINCT
		ENCOUNTER.ENCNTR_ID,
		ENCOUNTER.PERSON_ID,
		TRUNC((TRUNC(pi_from_gmt(ENCOUNTER.REG_DT_TM, 'America/Chicago')) - TRUNC(pi_from_gmt(PERSON.BIRTH_DT_TM, 'America/Chicago'))) / 365.25, 0) AS AGE,
		pi_get_cv_display(PERSON.SEX_CD) AS SEX,
		pi_get_cv_display(PERSON.RACE_CD) AS RACE,
		pi_get_cv_display(PERSON.ETHNIC_GRP_CD) AS ETHNICITY,
		ENCOUNTER.DISCH_DT_TM - ENCOUNTER.REG_DT_TM AS LOS,
		pi_from_gmt(ENCOUNTER.REG_DT_TM, 'America/Chicago') AS ADMIT_DATETIME,
		pi_from_gmt(ENCOUNTER.DISCH_DT_TM, 'America/Chicago') AS DISCH_DATETIME,
		pi_get_cv_display(ENCOUNTER.ENCNTR_TYPE_CLASS_CD) AS ENCNTR_TYPE_CLASS,
		pi_get_cv_display(ENCOUNTER.LOC_NURSE_UNIT_CD) AS NURSE_UNIT,
		pi_get_cv_display(ENCOUNTER.MED_SERVICE_CD) AS MED_SERVICE,
		pi_get_cv_display(ENCOUNTER.DISCH_DISPOSITION_CD) AS DISCH_DISPOSITION
	FROM
		ENCOUNTER,
		PERSON
	WHERE
		ENCOUNTER.ORGANIZATION_ID = 1 -- Memorial Hermann Hospital
		AND ENCOUNTER.DISCH_DT_TM BETWEEN
			DECODE(
				@Prompt('Choose date range', 'A', {'Last Week', 'Last Month', 'User-defined'}, mono, free, , , User:0),
				'Last Week', pi_to_gmt(TRUNC(SYSDATE - 7, 'DAY'), 'America/Chicago'),
				'Last Month', pi_to_gmt(TRUNC(ADD_MONTHS(SYSDATE, -1), 'MONTH'), 'America/Chicago'),
				'User-defined', pi_to_gmt(
					TO_DATE(
						@Prompt('Enter begin date', 'D', , mono, free, persistent, {'07/01/2019 00:00:00'}, User:1),
						pi_get_dm_info_char_gen('Date Format Mask|FT','PI EXP|Systems Configuration|Date Format Mask')
					),
					pi_time_zone(1, 'America/Chicago')
				)
			)
			AND DECODE(
				@Prompt('Choose date range', 'A', {'Last Week', 'Last Month', 'User-defined'}, mono, free, , , User:0),
				'Last Week', pi_to_gmt(TRUNC(SYSDATE, 'DAY') - 1/86400, 'America/Chicago'),
				'Last Month', pi_to_gmt(TRUNC(SYSDATE, 'MONTH') - 1/86400, 'America/Chicago'),
				'User-defined', pi_to_gmt(
					TO_DATE(
						@Prompt('Enter end date', 'D', , mono, free, persistent, {'07/01/2024 00:00:00'}, User:2),
						pi_get_dm_info_char_gen('Date Format Mask|FT','PI EXP|Systems Configuration|Date Format Mask')
					) - 1/86400,
					pi_time_zone(1, 'America/Chicago')
				)
			)		
		AND ENCOUNTER.LOC_FACILITY_CD IN (
			3310, -- HH HERMANN
			-- 3796, -- HC Childrens
			-- 3821, -- HH Clinics
			3822, -- HH Trans Care
			3823 -- HH Rehab
		)
		AND ENCOUNTER.ENCNTR_TYPE_CLASS_CD IN (
			42631, -- Inpatient
			-- 55851, -- Emergency
			688523 -- Observation
		)
		AND ENCOUNTER.PERSON_ID = PERSON.PERSON_ID
		AND TRUNC((TRUNC(pi_from_gmt(ENCOUNTER.REG_DT_TM, 'America/Chicago')) - TRUNC(pi_from_gmt(PERSON.BIRTH_DT_TM, 'America/Chicago'))) / 365.25, 0) >= 18
), PATIENTS AS (
	SELECT DISTINCT
		DISCHARGES.*,
		pi_get_cv_display(ORDERS.CATALOG_CD) AS MEDICATION
		-- pi_from_gmt(ORDERS.ORIG_ORDER_DT_TM, 'America/Chicago') AS ORDER_DATETIME,
	FROM
		DISCHARGES,
		ORDERS
	WHERE
		DISCHARGES.ENCNTR_ID = ORDERS.ENCNTR_ID
		AND DISCHARGES.PERSON_ID = ORDERS.PERSON_ID
		AND ORDERS.CATALOG_CD IN (
			9902731, -- warfarin
			9907573, -- enoxaparin
			14563141, -- fondaparinux
			545371153, -- dabigatran
			642177882, -- rivaroxaban
			894197557, -- apixaban
			1466817855 -- edoxaban
		)
		AND ORDERS.CATALOG_TYPE_CD = 1363 -- Pharmacy
		AND	ORDERS.TEMPLATE_ORDER_FLAG IN (0, 1)
		AND ORDERS.ORIG_ORD_AS_FLAG = 1 -- Prescription/Discharge Order
), DISCH_DIAGNOSIS AS (
	SELECT DISTINCT
		PATIENTS.ENCNTR_ID,
		-- DIAGNOSIS.DIAG_PRIORITY,
		NOMENCLATURE.SOURCE_IDENTIFIER AS PRIMARY_ICD10_CODE,
		NOMENCLATURE.SOURCE_STRING AS PRIMARY_ICD10_DESCRIPTION
	FROM
		DIAGNOSIS,
		NOMENCLATURE,
		PATIENTS
	WHERE
		PATIENTS.ENCNTR_ID = DIAGNOSIS.ENCNTR_ID
		AND DIAGNOSIS.DIAG_TYPE_CD = 26244 -- Final
		AND DIAGNOSIS.DIAG_PRIORITY = 1
		AND DIAGNOSIS.NOMENCLATURE_ID = NOMENCLATURE.NOMENCLATURE_ID
		-- AND REGEXP_INSTR(NOMENCLATURE.SOURCE_IDENTIFIER, '^E08|^E10|^E78|^I63|^I68|^F17.2|^I48|^I61.5|^I46') > 0 
		AND NOMENCLATURE.SOURCE_VOCABULARY_CD = 641836527 -- ICD-10-CM
		AND NOMENCLATURE.PRINCIPLE_TYPE_CD = 751 -- Disease or Syndrome
), ANTICOAG_DIAGNOSIS AS (
	SELECT DISTINCT
		PATIENTS.ENCNTR_ID,
		-- DIAGNOSIS.DIAG_PRIORITY,
		-- NOMENCLATURE.SOURCE_IDENTIFIER AS ICD10_CODE,
		-- NOMENCLATURE.SOURCE_STRING AS ICD10_DESCRIPTION,
		CASE
			WHEN REGEXP_INSTR(NOMENCLATURE.SOURCE_IDENTIFIER, '^I26') > 0 THEN 'PE'
			WHEN REGEXP_INSTR(NOMENCLATURE.SOURCE_IDENTIFIER, '^I82') > 0 THEN 'DVT'
 			WHEN REGEXP_INSTR(NOMENCLATURE.SOURCE_IDENTIFIER, '^I48') > 0 THEN 'AFIB'
			WHEN REGEXP_INSTR(NOMENCLATURE.SOURCE_IDENTIFIER, '^Z95.2') > 0 THEN 'VALVE'
		END AS ICD10_ANTICOAG,
		'TRUE' AS ICD_VALUE
	FROM
		DIAGNOSIS,
		NOMENCLATURE,
		PATIENTS
	WHERE
		PATIENTS.ENCNTR_ID = DIAGNOSIS.ENCNTR_ID
		AND DIAGNOSIS.DIAG_TYPE_CD = 26244 -- Final
		-- AND DIAGNOSIS.DIAG_PRIORITY = 1
		AND DIAGNOSIS.NOMENCLATURE_ID = NOMENCLATURE.NOMENCLATURE_ID
		AND REGEXP_INSTR(NOMENCLATURE.SOURCE_IDENTIFIER, '^I26|^I82|^I48|^Z95.2') > 0 
		AND NOMENCLATURE.SOURCE_VOCABULARY_CD = 641836527 -- ICD-10-CM
		AND NOMENCLATURE.PRINCIPLE_TYPE_CD = 751 -- Disease or Syndrome
), DIAG_PIVOT AS (
	SELECT * FROM ANTICOAG_DIAGNOSIS
	PIVOT(
		MIN(ICD_VALUE) FOR ICD10_ANTICOAG IN (
			'AFIB' AS AFIB,
			'DVT' AS DVT,
			'PE' AS PE,
			'VALVE' AS VALVE
		)
	)
), INSUR_PLANS AS (
	SELECT DISTINCT
		PATIENTS.ENCNTR_ID,
		ENCNTR_PLAN_RELTN.PRIORITY_SEQ,
		HEALTH_PLAN.PLAN_NAME
	FROM
		ENCNTR_PLAN_RELTN,
		HEALTH_PLAN,
		PATIENTS
	WHERE
		PATIENTS.ENCNTR_ID = ENCNTR_PLAN_RELTN.ENCNTR_ID
		-- AND ENCNTR_PLAN_RELTN.PRIORITY_SEQ = 1
		AND ENCNTR_PLAN_RELTN.END_EFFECTIVE_DT_TM > pi_to_gmt(SYSDATE, 'America/Chicago')
		AND ENCNTR_PLAN_RELTN.HEALTH_PLAN_ID = HEALTH_PLAN.HEALTH_PLAN_ID
), INSUR_ROLLUP AS (
	SELECT DISTINCT
		ENCNTR_ID,
		LISTAGG(PLAN_NAME, '; ') WITHIN GROUP (ORDER BY PRIORITY_SEQ) AS INSURANCE
	FROM
		INSUR_PLANS
	GROUP BY
		ENCNTR_ID
)

SELECT
	ENCNTR_ALIAS.ALIAS AS FIN,
	PATIENTS.*,
	DISCH_DIAGNOSIS.PRIMARY_ICD10_CODE,
	DISCH_DIAGNOSIS.PRIMARY_ICD10_DESCRIPTION,
	DIAG_PIVOT.AFIB,
	DIAG_PIVOT.DVT,
	DIAG_PIVOT.PE,
	DIAG_PIVOT.VALVE,
	INSUR_ROLLUP.INSURANCE
FROM
	DIAG_PIVOT,
	DISCH_DIAGNOSIS,
	ENCNTR_ALIAS,
	INSUR_ROLLUP,
	PATIENTS
WHERE
	PATIENTS.ENCNTR_ID = INSUR_ROLLUP.ENCNTR_ID(+)
	AND PATIENTS.ENCNTR_ID = DISCH_DIAGNOSIS.ENCNTR_ID(+)
	AND PATIENTS.ENCNTR_ID = DIAG_PIVOT.ENCNTR_ID(+)
	AND PATIENTS.ENCNTR_ID = ENCNTR_ALIAS.ENCNTR_ID
	AND ENCNTR_ALIAS.ENCNTR_ALIAS_TYPE_CD = 619 -- FIN NBR
	AND ENCNTR_ALIAS.ACTIVE_IND = 1